### ISSUE TITLE
[同步bug] 自建beta4 配合 app客户端

### ISSUE THREAD

**Issue by goodbest** [leanote/leanote#103]
server端 1.0beta4
client端  mac app 0.32

bug描述：
网页端新建一个notebook，添加1个笔记后save。
然后，客户端同步后，app里该notebook侧栏计数器依然显示为0，但笔记已经在了。

接下来。
在客户端里对该notebook改名，然后同步。
然后在网页端刷新，会发现新建了一个改好了名字的notebook

应该是对新notebook的同步逻辑有bug

**Comment by lealife** [comment]
Confirmed. 谢谢提供这么详细的步骤, 经经测试, 确实存在!

**Comment by lealife** [comment]
已修复, 感谢之!!
