### ISSUE TITLE
Is it possible to use Leanote without log in ?

### ISSUE THREAD

**Issue by ademcan** [leanote/leanote#106]
Thank you for this nice tool, it really looks beautiful and works well 
I think Leanote is the most suitable alternative to Evernote and co.
However, I was wondering why it is not possible to use Leanote locally without an account ? Apparently you always need an email and a password to use it. I would really appreciate a version that can be used locally without providing an email, maybe a username should be enough.

**Comment by lealife** [comment]
Thanks, Leanote is designing for multiple users, so you must login firstly. I think it's not a problem, because you will be always authorized once you have been logined.

**Comment by ademcan** [comment]
Thank you for your reply. I understand your decision. However, it looks like you always need to create an account on leanote.com to be able to use it (on the "Sign up" page at http://leanote.com/register). 
Once I installed Leanote locally it keeps asking me for my email and password.
I think that it might be good to have the option to create an account locally, without any online registration before. I understand that it might not be your priority or not in the plan at all, but I thought it would be good :)

**Comment by lealife** [comment]
I see, you are talking about the "Leanote desktop app" . 

We will take it into consideration.
