### ISSUE TITLE
脚本运行错误,只能运行在64位的系统么?

### ISSUE THREAD

**Issue by maboloshi** [leanote/leanote#120]
[root@localhost ~]# revel run github.com/leanote/leanote
~
~ revel! http://revel.github.io
~
INFO  2015/04/15 13:49:14 revel.go:320: Loaded module testrunner
INFO  2015/04/15 13:49:14 revel.go:320: Loaded module static
INFO  2015/04/15 13:49:14 run.go:57: Running leanote (github.com/leanote/leanote) in dev mode
TRACE 2015/04/15 13:49:14 run.go:58: Base path: /root/gopackage/src/github.com/leanote/leanote
TRACE 2015/04/15 13:49:14 template.go:191: Refreshing templates from [/root/gopackage/src/github.com/revel/revel/templates]
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.html
TRACE 2015/04/15 13:49:14 template.go:315: errors/403.html______________
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/403.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404-dev.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404-dev.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/404.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/405.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500-dev.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500-dev.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.html
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.json
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.txt
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.xml
TRACE 2015/04/15 13:49:14 template.go:276: adding template:  errors/500.xml
ERROR 2015/04/15 13:49:14 watcher.go:72: Failed to stat watched path /root/gopackage/src/github.com/leanote/leanote/tests : stat /root/gopackage/src/github.com/leanote/leanote/tests: no such file or directory
INFO  2015/04/15 13:49:14 harness.go:165: Listening on :80
TRACE 2015/04/15 13:49:44 harness.go:126: Rebuild
2015/04/15 13:49:44 reflect.go:724: Failed to generate name for field. Make sure the field name is valid.
2015/04/15 13:49:44 reflect.go:435: Failed to find import for arg of type: controllers.NoteOrContent
2015/04/15 13:49:45 reflect.go:101: Error scanning app source: lstat /root/gopackage/src/github.com/leanote/leanote/tests: no such file or directory
TRACE 2015/04/15 13:49:45 build.go:77: Exec: [/root/go/bin/go build -ldflags -X github.com/leanote/leanote/app.APP_VERSION "" -tags  -o /root/gopackage/bin/leanote github.com/leanote/leanote/app/tmp]
ERROR 2015/04/15 13:49:47 build.go:84: go build github.com/leanote/leanote/app/service: /root/go/pkg/tool/linux_386/8g: signal: killed

ERROR 2015/04/15 13:49:47 build.go:254: Failed to parse build errors:
 go build github.com/leanote/leanote/app/service: /root/go/pkg/tool/linux_386/8g: signal: killed
=================================
站点打开提示
Go Compilation Error
The Go code does not compile: See console for build error.
===============================================

另外运行 后Shadowsocks Server开不起来

**Comment by lealife** [comment]
可以运行在32位系统上的

**Comment by lealife** [comment]
leanote已提供二进制版, 可以至 http://leanote.org/#download 下载
