### ISSUE TITLE
附件大小和md文件同步

### ISSUE THREAD

**Issue by zhongwangninja** [leanote/leanote#138]
1. leanote的图片, 附件空间限制, 是指一个账户下所有图片不能超过120M, 还是单个文章图片不能超过120M;
2. 我使用leanote软件在本地创建了markdown文件, 点击了同步, 网页上还是看不到这篇文章, 创建普通文章是正常的.

**Comment by lealife** [comment]
"一个账户下所有图片不能超过120M", 这个方法不好, 以后会像evernote一样采用流量的方式
请使用ctrl+s保存并同步笔记. 请至 http://app.leanote.com 下载新版
