### ISSUE TITLE
客户端的marddown渲染有问题 windows7，软件是5.1版本

### ISSUE THREAD

**Issue by qianketian** [leanote/leanote#139]
![qq 20150511201947](https://cloud.githubusercontent.com/assets/10296101/7564603/e9d7aebe-f81a-11e4-9592-32bf16daf60a.png)
可以看到 左右的 文本顺序有问题

**Comment by lealife** [comment]
不能复现?

**Comment by lealife** [comment]
confirmed. 已确定

**Comment by lealife** [comment]
打开文档1, ctrl+e预览, 返回, 打开文档2. 此时文档2的预览会有文档1的预览
