### ISSUE TITLE
笔记中设置的标题、加黑在博客中无法正常显示

### ISSUE THREAD

**Issue by BenBeng** [leanote/leanote#142]
貌似没有什么复现的规律。

笔记：
![4f43b5afe943c307bcfe51252a785644](https://cloud.githubusercontent.com/assets/2141846/7722326/9c064bfc-ff11-11e4-9633-eec0317cde3d.png)

博客：
![0c35ac93c37fd3bc531baf6d3de062f3](https://cloud.githubusercontent.com/assets/2141846/7722331/a67d5f94-ff11-11e4-891e-ae2ce36a1124.png)

笔记：
![b6f05d12700751ed9b941dcd52d3306f](https://cloud.githubusercontent.com/assets/2141846/7722337/b3001fea-ff11-11e4-8a44-43d2718ec9eb.png)

博客：
![c9e1e1ebf0bef514c9c76413c94f5ffe](https://cloud.githubusercontent.com/assets/2141846/7722339/bab6579a-ff11-11e4-9161-7a35796d8f70.png)

**Comment by lealife** [comment]
加粗, 可能没有保存到数据库中, 请稍稍修改下, 再ctrl+s保存

**Comment by BenBeng** [comment]
试了一下，还是不行哦。标题的样式不对怎么解决呢？

**Comment by lealife** [comment]
博客主题的原因
