### ISSUE TITLE
笔记本目录无法删除

### ISSUE THREAD

**Issue by XQQinG** [leanote/leanote#153]
![3e07e5c8-7bfd-4792-bdfc-9df6f63b0d11](https://cloud.githubusercontent.com/assets/10509476/7874891/7c19a89c-05e8-11e5-9ce9-a34da30a9d22.png)
BMK目录下没有子目录和笔记，但是提示存在，无法删除。

**Comment by ThreeSZO** [comment]
看来是个老问题，我也遇到了。
