### ISSUE TITLE
Leanote API 能不能统一大小写 == 

### ISSUE THREAD

**Issue by czfshine** [leanote/leanote#160]
就像
>所有api的url前面带/api/, 如:
/api/user/info?userId=xxxx&token=xxxx
除了/auth/login, /auth/register外其它的都需要另外带参数token=xxxx

里面的userId和token ，userId的第一个字母U不大写，却在I大写，思维定势一下子就写错了，老是登陆失败，发现原来是大小写的问题。TAT

还有 `/notebook/getNotebooks`，为毛/notebook/没有大写。

最坑爹的是
>notebook/addNotebook 添加笔记本
参数: title(string), parentNotebookId(string, 父notebookId, 可空), seq(int) 排列
Method: POST
返回: 
错误: {Ok: false, Msg:""}
成功: type.Notebook

里面的parentNotebookId，大小写好奇怪= =

**Comment by tylerlong** [comment]
那叫做 [CamelCase](https://en.wikipedia.org/wiki/CamelCase)

> camelCase (Camelcase, CamelCase, camel case, camel caps or medial capitals) is the practice of writing compound words or phrases such that each word or abbreviation begins with a capital letter. Camel case may start with a capital or, especially in programming languages, with a lowercase letter.

**Comment by lealife** [comment]
notebook是一个单词, parentNotebookId有两个单词, 这是合理的.
