### ISSUE TITLE
建议：能否使用户在不同部署间分享

### ISSUE THREAD

**Issue by cooppor** [leanote/leanote#161]
知识在不同人之间传递，才会更有生命力，才会传递的更快，更远。 
假设，有这样的一个场景：A、B两个人，分别在各自的服务器部署了Leanote。如果，A有一个笔记需要分享给B，现有方式是：
1、公开为博客，并知B前来访问阅读，（如果是隐私，或保密的公开是不是不合适）；
2、通过其他方式发送给B，（是不是有点麻烦？）；

那么有没有一种可能，在服务端添加一个API，A用户可以通API，在笔记本，或笔记中点分享给其他用户的按钮，选择输入对方的服务路径，以及用户名，然后推送到B的服务端，当B打开客户端后，在笔记列表（或许可以有一个共享分类）中看到这篇分享。如果，这个需求及功能再做的细化点，那么就是可以设定，
1、B用户是否跟进该笔记的更新，也就是说B用户是否能够对该笔记进行同步，或者B是否有权限可以对这彷笔记进行协同编辑；
2、B在看到该分享后，是否可以采纳，并将该笔记转入自己的指定笔记分类中成为私有笔记，并可在某处标明来自A的分享，B用户也可以对此笔记进行正常的编辑操作。

总之，这是一个建议，具体是否合理，是否可行请考虑。

**Comment by lealife** [comment]
不同用户之间笔记的分享应该是一个主动的过程, 比如A看到了B的博客觉得很好, 将该博客添加到自己的笔记中.
