### ISSUE TITLE
运行run.bat提示错误  2015/06/24 16:36:15 revel.go:154: Failed to load app.conf: not found

### ISSUE THREAD

**Issue by oshell** [leanote/leanote#162]
2015/06/24 16:36:15 revel.go:154: Failed to load app.conf: not found

**Comment by 724899020** [comment]
我也遇到了同样问题，我是在centos7下面。

**Comment by oshell** [comment]
我是在win2008下.不过后来我把目录放在其他地方, 可以正常运行

**Comment by lealife** [comment]
很有可能是有多个leanote

**Comment by linux-mac** [comment]
多次启动时，要注意 leanote 和 revel 都需要 kill 掉
