### ISSUE TITLE
博客邮箱地址泄露

### ISSUE THREAD

**Issue by duguyipiao** [leanote/leanote#174]
如果没有更改，博客系统的默认用户名是用户邮箱，这容易使用邮箱地址泄露。从leanote++上就可以看到许多用户的邮箱，或者[Google](https://www.google.com/#q=inurl:gmail+site:blog.leanote.com)可以看到更多。建议隐藏用户邮箱，或者不使用邮箱作为用户名。

**Comment by bao3** [comment]
确实，非常严重。

**Comment by lealife** [comment]
确实
