### ISSUE TITLE
leanote特性，性能优化与安全性增强

### ISSUE THREAD

**Issue by duoyun** [leanote/leanote#190]
大致评估了下leanote，目前发现一些问题或者建议如下：
 0.routers修改，简单。首页博客列表超链接方式修改，只保留一个简洁的链接
    如p+id,这个完全是个人喜好，对之前已有内容影响较大
 1.博客首页展示方式：blog.index改为展现多用户的博客，目前为显示管理员的博客
 2.安全性增强：密码加密方式md5改为bcrypt（之前注册用户需要重置密码）
    我修改了下:
   https://github.com/leanote/leanote/pull/189
 3.性能优化：目前notes标识位太多,数据量大的时候对性能有很大影响：
     isBlog,isMarkdown,IsTrash,IsDeleted
    目前：删除笔记，IsTrash 设置为true；再删除废纸篓，IsDeleted为true。
    建议：没有将数据在后台库删除，数据多了会影响性能，建议物理删除；
          废纸篓功能可以将删除的notes移到一个新集合里。
          删掉普通笔记功能（富文本），只用Markdown？可去除isMarkdown

注：以上有的改动可能影响较大

**Comment by lealife** [comment]
你好, 密码加密方式md5改为bcrypt, 影响较大, 不能向下兼容, 不便迁移

**Comment by lealife** [comment]
"建议：没有将数据在后台库删除，数据多了会影响性能，建议物理删除；" 以后做一个功能将IsDeleted的数据物理删除, 为什么不物理删除是因为多客户端同步的原因. 如果物理删除了, 客户端就无法知道是否删除

**Comment by lealife** [comment]
"删掉普通笔记功能（富文本），只用Markdown？可去除isMarkdown"? 不明白

**Comment by duoyun** [comment]
@lealife 同步问题看看能不能想其他办法解决；Markdown是说笔记只支持Markdown就可以了，富文本编辑器删掉，保持坚定，notes表里就不需要isMarkdown去标记了。

**Comment by lealife** [comment]
"Markdown是说笔记只支持Markdown就可以了，富文本编辑器删掉，保持简洁" 不行的, 不是所有用户都用markdown编辑器的
