### ISSUE TITLE
如何将leanote放在二级路径下面，如http://xxx.com/leanote

### ISSUE THREAD

**Issue by niphor** [leanote/leanote#194]
请问 如果要将leanote放置在二级路径下面，该如何配置？

我看输出的页面中都是以'/'开头的，导致路径全变成根目录了...

我用的是Nginx

谢谢。

**Comment by lealife** [comment]
不可以弄个二级域名吗?

**Comment by lealife** [comment]
这种方式, 弄个二级域名更好

**Comment by niphor** [comment]
@lealife 由于一些众所周知的原因，所以启用了SSL，因为是自用，不是 wildcard，域名下挂了几个不同的工具，所以放二级目录省力些...

能放二级路径么？具体怎么配置？

**Comment by lealife** [comment]
还真不能支持, 很多都是绝对路径, 比如/note, /js, /public, /images

**Comment by niphor** [comment]
@lealife 

好吧，希望考虑支持...

另外 希望能把Blog 精简掉...毕竟这不是核心功能...

另外 我在 bananpro上用 go1.5编译之后，用admin登录，进`用户管理`时，无限等待

由于没什么错误输出，而且等着等着直接整个开发板的Ubuntu都卡宕机了，SSH都连不上了，所以并不能提供日志给你，不好意思...

**Comment by lealife** [comment]
登录有问题, 很可能就是数据连接问题

**Comment by lealife** [comment]
"另外 希望能把Blog 精简掉...毕竟这不是核心功能...", 很多用户都有这个需求, 并且要求增强这个功能, 所以...

**Comment by wangxiaoyao** [comment]
有个问题请教一下各位前辈： 我已经在自己的服务器搭建了leanote。现在希望修改我自己博客的域名为主域名。 而不是leanote的注册页。 我应该怎么操作。 万分感谢
