### ISSUE TITLE
开发版admin用户后台管理无法删除用户

### ISSUE THREAD

**Issue by ferstar** [leanote/leanote#200]
后台管理界面功能还有待丰富～
![deepinscrot-5927](https://cloud.githubusercontent.com/assets/2854276/9756316/d4a6e8e8-570b-11e5-981e-c420686c115c.png)

**Comment by lealife** [comment]
对, 删除用户功能没有

**Comment by lealife** [comment]
欢迎提交pull request

**Comment by KennyDiff** [comment]
我也很想知道2年了，开发版后台为何无法删除演示用户数据？ 这个issue

**Comment by boyxiaopang** [comment]
竟然无法删除用户。。。。

**Comment by FreeApe** [comment]
现在也还不能删除

**Comment by whuwangyong** [comment]
估计缺人吧

**Comment by FreeApe** [comment]
@whuwangyong  这是个小功能而且常用的功能，两年多了。。。

**Comment by Mrzyxing** [comment]
又是一个2年

**Comment by lealife** [comment]
欢迎提交pull request

**Comment by lixchen** [comment]
发自我的 iPhone

**Comment by xueluofeng** [comment]
现在是2019年,还是没有

**Comment by ljw4010** [comment]
他们是不想开放吧

**Comment by iliuweiming** [comment]
都9102年了，还没修复
