### ISSUE TITLE
搭建问题 不太了解这个所需source是什么

### ISSUE THREAD

**Issue by wb670** [leanote/leanote#205]
TRACE 2015/09/12 15:16:04 build.go:94: Exec: [/datadb/mmc/go/bin/go build -ldflags -X github.com/leanote/leanote/app.APP_VERSION "" -tags  -o /datadb/mmc/gopackage/bin/revel.d/github.com/leanote/leanote/leanote github.com/leanote/leanote/app/tmp]
ERROR 2015/09/12 15:16:27 build.go:101: go build github.com/leanote/leanote/tests: no buildable Go source files in /datadb/mmc/gopackage/src/github.com/leanote/leanote/tests

ERROR 2015/09/12 15:16:27 build.go:298: Failed to parse build errors:
 go build github.com/leanote/leanote/tests: no buildable Go source files in /datadb/mmc/gopackage/src/github.com/leanote/leanote/tests

**Comment by lealife** [comment]
不好意思, 已修复, 请更新源码. git pull
