### ISSUE TITLE
win 下安装源码，运行revel命令后，访问网页报错

### ISSUE THREAD

**Issue by beginnor** [leanote/leanote#208]
INFO  2015/09/16 22:15:42 harness.go:165: Listening on :80
TRACE 2015/09/16 22:15:46 harness.go:126: Rebuild
INFO  2015/09/16 22:15:46 build.go:172: Cleaning dir tmp
INFO  2015/09/16 22:15:46 build.go:172: Cleaning dir routes
ERROR 2015/09/16 22:15:46 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leano
te/app
WARN  2015/09/16 22:15:46 reflect.go:94: Skipping code path C:\golang\src/github.com\leanote\leanote/app
ERROR 2015/09/16 22:15:46 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src\github.com\revel\modules
\static/app
WARN  2015/09/16 22:15:46 reflect.go:94: Skipping code path C:\golang\src\github.com\revel\modules\static/app
ERROR 2015/09/16 22:15:46 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src\github.com\revel\modules
\testrunner/app
WARN  2015/09/16 22:15:46 reflect.go:94: Skipping code path C:\golang\src\github.com\revel\modules\testrunner/app
ERROR 2015/09/16 22:15:46 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leano
te/tests
WARN  2015/09/16 22:15:46 reflect.go:94: Skipping code path C:\golang\src/github.com\leanote\leanote/tests
2015/09/16 22:15:46 server.go:1775: http: panic serving [::1]:54031: runtime error: invalid memory address or nil pointe
r dereference
goroutine 26 [running]:
net/http.func·011()
        c:/go/src/net/http/server.go:1130 +0xc2
github.com/revel/cmd/harness.(*SourceInfo).ControllerSpecs(0x0, 0x0, 0x0, 0x0)
        C:/golang/src/github.com/revel/cmd/harness/reflect.go:676 +0x41
github.com/revel/cmd/harness.Build(0x0, 0x0, 0x0, 0x1, 0x0)
        C:/golang/src/github.com/revel/cmd/harness/build.go:42 +0x284
github.com/revel/cmd/harness.(*Harness).Refresh(0xc0820ae360, 0xc0820eca01)
        C:/golang/src/github.com/revel/cmd/harness/harness.go:127 +0x148
github.com/revel/revel.(*Watcher).Notify(0xc0820f2eb0, 0x0)
        C:/golang/src/github.com/revel/revel/watcher.go:188 +0x332
github.com/revel/cmd/harness.(*Harness).ServeHTTP(0xc0820ae360, 0x134d58, 0xc0820e26e0, 0xc0820ff040)
        C:/golang/src/github.com/revel/cmd/harness/harness.go:63 +0x9a
net/http.serverHandler.ServeHTTP(0xc0820ede00, 0x134d58, 0xc0820e26e0, 0xc0820ff040)
        c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc0820e2640)
        c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x365
TRACE 2015/09/16 22:15:47 harness.go:126: Rebuild
INFO  2015/09/16 22:15:47 build.go:172: Cleaning dir tmp
INFO  2015/09/16 22:15:47 build.go:172: Cleaning dir routes
ERROR 2015/09/16 22:15:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leano
te/app
WARN  2015/09/16 22:15:47 reflect.go:94: Skipping code path C:\golang\src/github.com\leanote\leanote/app
ERROR 2015/09/16 22:15:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src\github.com\revel\modules
\static/app
WARN  2015/09/16 22:15:47 reflect.go:94: Skipping code path C:\golang\src\github.com\revel\modules\static/app
ERROR 2015/09/16 22:15:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src\github.com\revel\modules
\testrunner/app
WARN  2015/09/16 22:15:47 reflect.go:94: Skipping code path C:\golang\src\github.com\revel\modules\testrunner/app
ERROR 2015/09/16 22:15:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leano
te/tests
WARN  2015/09/16 22:15:47 reflect.go:94: Skipping code path C:\golang\src/github.com\leanote\leanote/tests
2015/09/16 22:15:47 server.go:1775: http: panic serving [::1]:54032: runtime error: invalid memory address or nil pointe
r dereference
goroutine 27 [running]:
net/http.func·011()
        c:/go/src/net/http/server.go:1130 +0xc2
github.com/revel/cmd/harness.(*SourceInfo).ControllerSpecs(0x0, 0x0, 0x0, 0x0)
        C:/golang/src/github.com/revel/cmd/harness/reflect.go:676 +0x41
github.com/revel/cmd/harness.Build(0x0, 0x0, 0x0, 0x1, 0x0)
        C:/golang/src/github.com/revel/cmd/harness/build.go:42 +0x284
github.com/revel/cmd/harness.(*Harness).Refresh(0xc0820ae360, 0xc0820eca01)
        C:/golang/src/github.com/revel/cmd/harness/harness.go:127 +0x148
github.com/revel/revel.(*Watcher).Notify(0xc0820f2eb0, 0x0)
        C:/golang/src/github.com/revel/revel/watcher.go:188 +0x332
github.com/revel/cmd/harness.(*Harness).ServeHTTP(0xc0820ae360, 0x134d58, 0xc0820e2820, 0xc0820ff380)
        C:/golang/src/github.com/revel/cmd/harness/harness.go:63 +0x9a
net/http.serverHandler.ServeHTTP(0xc0820ede00, 0x134d58, 0xc0820e2820, 0xc0820ff380)
        c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc0820e2780)
        c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x365
TRACE 2015/09/16 22:18:47 harness.go:126: Rebuild
INFO  2015/09/16 22:18:47 build.go:172: Cleaning dir tmp
INFO  2015/09/16 22:18:47 build.go:172: Cleaning dir routes
ERROR 2015/09/16 22:18:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leano
te/app
WARN  2015/09/16 22:18:47 reflect.go:94: Skipping code path C:\golang\src/github.com\leanote\leanote/app
ERROR 2015/09/16 22:18:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src\github.com\revel\modules
\static/app
WARN  2015/09/16 22:18:47 reflect.go:94: Skipping code path C:\golang\src\github.com\revel\modules\static/app
ERROR 2015/09/16 22:18:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src\github.com\revel\modules
\testrunner/app
WARN  2015/09/16 22:18:47 reflect.go:94: Skipping code path C:\golang\src\github.com\revel\modules\testrunner/app
ERROR 2015/09/16 22:18:47 reflect.go:775: Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leano
te/tests
WARN  2015/09/16 22:18:47 reflect.go:94: Skipping code path C:\golang\src/github.com\leanote\leanote/tests
2015/09/16 22:18:47 server.go:1775: http: panic serving [::1]:54151: runtime error: invalid memory address or nil pointe
r dereference
goroutine 28 [running]:
net/http.func·011()
        c:/go/src/net/http/server.go:1130 +0xc2
github.com/revel/cmd/harness.(*SourceInfo).ControllerSpecs(0x0, 0x0, 0x0, 0x0)
        C:/golang/src/github.com/revel/cmd/harness/reflect.go:676 +0x41
github.com/revel/cmd/harness.Build(0x0, 0x0, 0x0, 0x1, 0x0)
        C:/golang/src/github.com/revel/cmd/harness/build.go:42 +0x284
github.com/revel/cmd/harness.(*Harness).Refresh(0xc0820ae360, 0xc0820eca01)
        C:/golang/src/github.com/revel/cmd/harness/harness.go:127 +0x148
github.com/revel/revel.(*Watcher).Notify(0xc0820f2eb0, 0x0)
        C:/golang/src/github.com/revel/revel/watcher.go:188 +0x332
github.com/revel/cmd/harness.(*Harness).ServeHTTP(0xc0820ae360, 0x134d58, 0xc0820e2280, 0xc0820d4000)
        C:/golang/src/github.com/revel/cmd/harness/harness.go:63 +0x9a
net/http.serverHandler.ServeHTTP(0xc0820ede00, 0x134d58, 0xc0820e2280, 0xc0820d4000)
        c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc0820e21e0)
        c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x365

**Comment by lealife** [comment]
Unexpected! Code path is not in GOPATH: C:\golang\src/github.com\leanote\leanote/app

你的GOPATH没有设对, GOPATH是C:\golang吗?
