### ISSUE TITLE
在客户端编辑md文章,公开到博客后,在主页显示详情里md渲染失效的问题

### ISSUE THREAD

**Issue by succlz123** [leanote/leanote#219]
在客户端编辑md文章,公开到博客后,在主页显示详情里md渲染失效的问题
同样的在网页上编辑修改md文件后在公开到博客后,在显示详情里渲染是正常的
http://rainkong.leanote.com/
比如这个人的主页里
Mac截屏快捷键
明显就是在客户端里编辑后公开的

**Comment by lealife** [comment]
你好, 确实有这个问题, 因为web端会将渲染好的html保存, 这是客户端的问题. 已添加到客户端issue中: https://github.com/leanote/desktop-app/issues/54
