### ISSUE TITLE
使用中的几个问题

### ISSUE THREAD

**Issue by clark010** [leanote/leanote#221]
1、个人的头像的设置图片需要特定的格式？电脑的图片传了之后无法有效显示
2、选的主题中的图片也无法有效显示
3、网页端的删除操作不能同步到mac app上，反过来也一样

**Comment by stanwu** [comment]
我用 PNG 格式, 可以正常顯示
![screen shot 2015-10-09 at 11 35 15 pm](https://cloud.githubusercontent.com/assets/121381/10398236/7de782d4-6ede-11e5-9eda-22fe6aba505b.png)

**Comment by lealife** [comment]
1,2 没有这两个问题吧, 3也没有. 删除后执行同步操作
