### ISSUE TITLE
单独部署leanote使用nginx代理到https之后博客页面中地址输出为http形式导致firefox在https情况下 block 掉http部分内容

### ISSUE THREAD

**Issue by bluesky4485** [leanote/leanote#228]
样式如下：基本上没法看了。
![Imgur](http://i.imgur.com/SRwocnG.jpg)

查看网页源码css和js文件全部都不是相对路径，变成http开始的绝对路径了，但是也有部分css是相对路径的。另外，还有博客的主页地址，类似http://xxx.com/blog/abc@gmail.com ，这种也是绝对路径。

附：在leanote的app.conf里面site.url配置的是http://xxx.com ,是通过nginx转发的https。

在note页面基本上都是使用的相对路径，不存在css或js在https页面中使用http链接的情况。仔细检查了下好像就note页面的博客地址使用的是http的绝对路径。

建议看是不是将这些url的输出统一一下？虽说将site.url配置成https://xxx.com 是可以解决这个问题的。 

实在不行在QA里面配置https部分加点说明吧，如果要配置https访问的话建议将site.url配置成https://xxx.com

**Comment by bluesky4485** [comment]
我已经编辑过QA了，在最下面site.url部分加了一段关于配置https的说明了。

**Comment by lealife** [comment]
谢谢 可以配置nginx使得http和https同时支持

**Comment by bluesky4485** [comment]
@lealife 嗯，主要是我强制将http转到https了，相当于不支持http形式访问，会自动跳转到https的时候，就会出现我说的这个问题。

我想了解下后续是否会统一相对路径和绝对路径的输出问题一劳永逸的解决掉，还是说没有计划修改，暂时就在QA中说明仅部署https形式的site.url的配置问题？

**Comment by lealife** [comment]
用相对路径会好些, 谢谢!
