### ISSUE TITLE
数据库初始化，抛出异常

### ISSUE THREAD

**Issue by DengKe1994** [leanote/leanote#229]
INFO  2015/10/12 10:40:36 Debug.go:10: mongodb://localhost:27017/leanote
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4761c1]

goroutine 1 [running]:
gopkg.in/mgo%2ev2.(*Session).SetMode(0x0, 0x1, 0x1)
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/session.go:1470 +0x311
github.com/leanote/leanote/app/db.Init(0xc82031e7b0, 0x21, 0xc8200956aa, 0x7)
	/Users/dengka/code/go/src/github.com/leanote/leanote/app/db/Mgo.go:108 +0x618
github.com/leanote/leanote/app.init.1.func26()
	/Users/dengka/code/go/src/github.com/leanote/leanote/app/init.go:403 +0x33
github.com/revel/revel.runStartupHooks()
	/Users/dengka/code/go/src/github.com/revel/revel/server.go:135 +0x5b
github.com/revel/revel.Run(0xe975)
	/Users/dengka/code/go/src/github.com/revel/revel/server.go:92 +0x21d
main.main()
	/Users/dengka/code/go/src/github.com/leanote/leanote/app/tmp/main.go:2306 +0x45c71

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 33 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201415e0, 0x1)
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/server.go:297 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/server.go:90 +0x162

goroutine 26 [sleep]:
time.Sleep(0x1dcd6500)
	/usr/local/go/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc82030a800)
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/cluster.go:383 +0x484
created by gopkg.in/mgo%2ev2.newCluster
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/cluster.go:76 +0x1d0

goroutine 52 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201416c0, 0x1)
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/server.go:297 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/Users/dengka/code/go/src/gopkg.in/mgo.v2/server.go:90 +0x162

Session.SetMode(mgo.Monotonic, true)这句出的问题。
Go小白，求帮忙看下。

**Comment by lealife** [comment]
可以用mongo命令连接mongodb吗?

**Comment by DengKe1994** [comment]
可以。找到问题了，设置了用户名、密码可以，没权限控制不成。lealife可以重现下。
