### ISSUE TITLE
leanote和nginx的部署时的疑问

### ISSUE THREAD

**Issue by Blackrose** [leanote/leanote#230]
你好，我在ARM板子上部署leanote，然后用nginx proxy来访问leanote，我的配置如下：

leanote: app.conf里面的siteurl改为note.abc.com，Port是80，运行命令是revel run github.com/leanote/leanote dev 9000
nginx: proxy_pass 127.0.0.1:9000

这样设置后可以正常访问。对后面的参数有疑问，为什么不能直接在siteurl里写成127.0.0.1:9000，这样nginx也可以直接代理(不太懂GO语言开发，请见凉)

**Comment by lealife** [comment]
site.url 请配置成外网要访问的域名

**Comment by lealife** [comment]
这和Go语言无关

**Comment by lealife** [comment]
你可以在app.conf中配置成:
```

http.port=9000

site.url=http://a.com
````
然后直接运行即可 revel run github.com/leanote/leanote
