### ISSUE TITLE
mac客户端笔记错位

### ISSUE THREAD

**Issue by quheng** [leanote/leanote#232]
使用mac客户端时常会发生不同笔记错乱，丢失了不少笔记。

**Comment by lealife** [comment]
能描述下过程吗?

**Comment by quheng** [comment]
系统版本是10.11.1 (15B42)
在编辑过一个笔记之后，切换到其他笔记（以某种模式，比如说编辑状态）会被覆盖掉，详细的复现过程我也没法提供，但是很大几率会发生。且mac客户端的历史记录不能使用，最后在web上的历史记录才恢复。
