### ISSUE TITLE
自建leanote，无法添加图片

### ISSUE THREAD

**Issue by Auues** [leanote/leanote#237]
自建leanote，无法添加图片，仅能复制粘贴，点击编辑栏的添加图片按钮添加图片如下所示：
![l 6a220 b6q2uriazd5nxwu](https://cloud.githubusercontent.com/assets/10848897/10573199/c3da1686-7680-11e5-82cd-656250afe49b.jpg)

**Comment by lealife** [comment]
你好, 有没有外网地址, 我看看

**Comment by lealife** [comment]
什么版本? 
是开发版还是二进制版?

**Comment by Auues** [comment]
是开发版。有绑定域名。QQ在的话我群里发私信

**Comment by lealife** [comment]
![image](https://cloud.githubusercontent.com/assets/1699428/10602232/b1da803c-7749-11e5-8ace-f6c3abaee886.png)
丢失album目录
