### ISSUE TITLE
Undo 功能有 bug?

### ISSUE THREAD

**Issue by sdnian** [leanote/leanote#246]
leanote 的 undo 有 bug? 或者本来就是这样的功能?

当我用 leanote 编辑不同的笔记，假设我先编辑 笔记A，完成后，新增一个 笔记B，这时如果在 笔记B 一直做 Undo，就是把 笔记B 修改过的内容都 Undo 完之后，下一次再 Undo 会出现 笔记A 的资料. 

应该只能 Undo 当前笔记的内容才是比较合理的功能。

**Comment by lealife** [comment]
这是一个BUG

**Comment by lealife** [comment]
1.4 修复
