### ISSUE TITLE
请问一下，在服务器该如何给数据做备份？

### ISSUE THREAD

**Issue by ziqin-git** [leanote/leanote#262]
使用管理员权限在后台备份时出现错误，显示"exit status 127"。之后使用mongodb数据库自己的备份命令进行备份，但是使用mongorestore命令还原之后没有任何变化，之前保存的笔记没有恢复。那么在服务器端该如何备份数据库呢？
![default](https://cloud.githubusercontent.com/assets/13920204/11237390/93a1b422-8e1a-11e5-9b39-ee7fef247ea4.jpg)

**Comment by lealife** [comment]
这是一个bug, 不支持mongodb v3. 你可以自己备份mongodb数据库

除了数据库外, 你还要备份上传的图片/附件, 在 leanote的 ** files ** 目录

**Comment by ziqin-git** [comment]
谢谢，解决了。

**Comment by qq1012827513** [comment]
> 谢谢，解决了。使用mongodb自带的命令备份数据库，复制files下的文档就可以了。

老哥怎么操作的啊 我也报错。。

**Comment by pengdongliang** [comment]
> > 谢谢，解决了。使用mongodb自带的命令备份数据库，复制文件下的文档就可以了。
> 
> 老哥怎么操作的啊我也报错。。

****

## **备份数据与恢复**
- **注意, 不要在网页翻译成中文的时候操作, 那样按钮点了没反应的**

- 登录网页端后，可以进入管理界面

- 先选择 `mongodb工具配置` 选项来设置备份和恢复的启动程序的绝对路径
```
# mongodump路径
比如: /home/mongodb-linux-x86_64-3.0.1/bin/mongodump

# mongorestore路径
比如: /home/mongodb-linux-x86_64-3.0.1/bin/mongorestore
```

- 选择后台下拉框里的 `后台管理`, 在左边数据(Data)选项里选择`备份与恢复`

- 需要恢复的数据要放入备份文件夹中, 在 `后台管理` 选项里的路径就是. 如下:
```
/home/leanote/bin/src/github.com/leanote/leanote/mongodb_backup/2019_October_7_1570429750
```

**Comment by Noevil0** [comment]
> > > 谢谢，解决了。使用mongodb自带的命令备份数据库，复制文件下的文档就可以了。
> > 
> > 
> > 老哥怎么操作的啊我也报错。。
> 
> ## **备份数据与恢复**
> * **注意，不要在网页翻译成中文的时候操作，那样按钮点了没反应的**
> * 登录网页端后，可以进入管理界面
> * 先选择`mongodb工具配置`选项来设置备份和恢复的启动程序的绝对路径
> 
> ```
> # mongodump路径
> 比如: /home/mongodb-linux-x86_64-3.0.1/bin/mongodump
> 
> # mongorestore路径
> 比如: /home/mongodb-linux-x86_64-3.0.1/bin/mongorestore
> ```
> 
> * 选择后台拖动框里的`后台管理`，在左边数据（Data）选项里选择`备份与恢复`
> * 需要恢复的数据要放入备份文件夹中，在`后台管理`选项里的路径就是。如下：
> 
> ```
> /home/leanote/bin/src/github.com/leanote/leanote/mongodb_backup/2019_October_7_1570429750
> ```

大哥你弄好了吗我设置绝对路径后显示状态1
