### ISSUE TITLE
强烈建议提供一下linux arm的二进制包

### ISSUE THREAD

**Issue by cooppor** [leanote/leanote#264]
非常需要这个，之前gogs 也没有linux arm版本二进制包，提了需求后，官方就提供了，希望Leanote不久的将来也可以提供，非常感谢。

**Comment by lealife** [comment]
谢谢, 会支持的, 1.4 版支持.

**Comment by cooppor** [comment]
嗯，谢谢采纳！打包对我们会的人来说其实不难，但是对不会的就很麻烦的感觉，不打包的情况下在运行服务后，第一次请求服务的时候非常非常慢。
