### ISSUE TITLE
升级1.0版本后复制粘贴会混乱

### ISSUE THREAD

**Issue by fulvaz** [leanote/leanote#271]
系统:ubuntu 14.04 LTS
版本:1.0
现象:在markdown笔记中,粘贴文字到笔记中,会粘贴两次,即,复制内容
>By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun: Reader, Writer, Formatter, CloseNotifier etc.

粘贴结果:
>By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun: Reader, Writer, Formatter, CloseNotifier etc.By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun: Reader, Writer, Formatter, CloseNotifier etc.
>

已经做过的尝试步骤:
将文字复制粘贴到gedit,gedit显示没有问题
将文字粘贴到gedit,再复制到leanote,leanote显示粘贴了两次

**Comment by lealife** [comment]
好的. 请使用右键粘贴暂时解决这个问题. 1.1版修复

**Comment by lealife** [comment]
Move to https://github.com/leanote/desktop-app/issues/98
