### ISSUE TITLE
web无法显示，但桌面客户端显示正常那个

### ISSUE THREAD

**Issue by gordonlgy** [leanote/leanote#278]
<iframe src="http://rcm-cn.amazon-adsystem.com/e/cm?t=gordonlgy-23&o=28&p=8&l=as1&asins=161954234X&IS1=1&ref=tf_til&fc1=000000&lt1=_blank&m=amazon&lc1=0000FF&bc1=FFFFFF&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
![qq 20151210174643](https://cloud.githubusercontent.com/assets/3354891/11712137/13e9855e-9f66-11e5-9cf4-7e6a4f5955e4.png)

**Comment by gordonlgy** [comment]
<iframe src="http://rcm-cn.amazon-adsystem.com/e/cm?t=gordonlgy-23&o=28&p=8&l=as1&asins=161954234X&IS1=1&ref=tf_til&fc1=000000&lt1=_blank&m=amazon&lc1=0000FF&bc1=FFFFFF&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>

**Comment by gordonlgy** [comment]
是亚马逊联盟的html code<iframe src="http://rcm-cn.amazon-adsystem.com/e/cm?t=gordonlgy-23&o=28&p=8&l=as1&asins=161954234X&IS1=1&ref=tf_til&fc1=000000&lt1=_blank&m=amazon&lc1=0000FF&bc1=FFFFFF&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>

**Comment by lealife** [comment]
adblock
