### ISSUE TITLE
在64位linux上安装32位leanote问题

### ISSUE THREAD

**Issue by hu895183198** [leanote/leanote#283]
作为第一次在Github上提交issue的新人，我整个人都是方的……由于不熟悉格式，可能代码贴上来会乱，忘见谅。
背景：小弟在Daocloud(http://www.daocloud.io/ )上申请了个胶囊云主机，想实际测试leanote搭建过程，如果可以直接在树莓派上搭建做笔记本服务器。Follow了安装指南（https://github.com/leanote/leanote/wiki/leanote-binary-distribution-installation-tutorial ）后，下载的是32位的binary包，在安装指南进行到：
$> bash run.sh (or sh run.sh)
报错，提示：
chmod: cannot access ‘/home/ubuntu/leanote/bin/leanote-linux-amd64’: No such file or directory
run.sh: line 29: /home/ubuntu/leanote/bin/leanote-linux-amd64: No such file or directory
第一反应是卧槽？！我下的是32位啊！当然不会有amd64文件夹啊，怎么会要求访问64位的文件夹呢？
好奇心驱使下，运行
$>vim run.sh
有一段代码是这样的：
if [ $bit = "64" ]
then
       bit="amd64"
else
       bit="386"
fi

script="$SCRIPTPATH/leanote-$osName-$bit"
代码大家都懂，于是小弟将if-else语句注释掉了，并在if-else语句后加上：
bit="386"
运行并访问成功。
我只想说麻烦各位开发人员在32位版的binary中直接把if-else语句去掉，32位机器运行当然没问题，64位的机器误下32位的binary就会有这个bug的。
以及安装指南中有处小错误：
在Import initial leanote data处
For mongodb v2:
$> mongorestore -h localhost -d leanote --directoryperdb /home/user1/gopackage/src/github.com/leanote/leanote/mongodb_backup/leanote_install_data/
由于版本迭代问题，最新版路径应为：
$> mongorestore -h localhost -d leanote --directoryperdb /home/user1/leanote/mongodb_backup/leanote_install_data/
mongodb v3同理。
完了写的有点多……小弟更方了怎么办……

**Comment by lealife** [comment]
你好, 关于导入Leanote路径的问题, 请直接在wiki上修改, 谢谢

**Comment by lealife** [comment]
关于32位, 64位的问题, 下次发布直接写死在run.sh中, 不通过判断

**Comment by hu895183198** [comment]
好的，多谢！
