### ISSUE TITLE
Mac 桌面版关闭

### ISSUE THREAD

**Issue by zzvv** [leanote/leanote#284]
执行 `command + w ` 关闭当前窗口，但发现是完全退出应用。

桌面版 视图设置没找到地方调配

blog 配置 未备案域名至二级域名，出现`阿里云error`

**Comment by lealife** [comment]
请及时在阿里云备案

**Comment by lealife** [comment]
"执行 command + w 关闭当前窗口，但发现是完全退出应用。" 移到桌面端仓库吧
