### ISSUE TITLE
Markdown语法高亮不正确

### ISSUE THREAD

**Issue by npbool** [leanote/leanote#286]
Markdown强调符号'\*'会和数学环境内的乘号'\*'配对，导致高亮错误，例如

<img width="398" alt="screen shot 2015-12-16 at 3 15 12 pm" src="https://cloud.githubusercontent.com/assets/1175364/11834487/e1de9f76-a407-11e5-9272-514e73b3eb32.png">

**Comment by lealife** [comment]
已确认
