### ISSUE TITLE
自建服务不能导出pdf

### ISSUE THREAD

**Issue by troywmz** [leanote/leanote#305]
我将leanote部署在安装centos 6的服务器上。其他功能都正常，就是不能将笔记导出为pdf文件。点击导出后没有反应，直接打开导出链接 `http://note.mysite.com/note/exportPdf?noteId=56a4ecde4b9d0c5fbf000` 显示 `error, no dir`。
查了源码，作为小白还是不太明白问题所在。服务器已经安装wkhtmltopdf，并且本地测试能够将html文件转为pdf文件。也在admin账户里设置了wkhtmltopdf路径。求解

**Comment by lealife** [comment]
这一行有问题 https://github.com/leanote/leanote/blob/dd9952c4532ac1e1bb7334ed43e58bc375241be7/app/controllers/NoteController.go#L421

估计是没有权限不能创建目录

**Comment by lealife** [comment]
你自己在本地创建一个目录试试, Leanote根目录下 files/export_pdf

**Comment by troywmz** [comment]
经测试是权限的问题，修改用户权限后能顺利导出，谢谢！
