### ISSUE TITLE
Are there plans for an import method?

### ISSUE THREAD

**Issue by JeffMelton** [leanote/leanote#312]
Do you have plans to roll out a way to import content from other services? I'm thinking primarily of Evernote, but being able to import an exported blog would be nice, too.

**Comment by lealife** [comment]
You can use [Leanote's desktop app](http://app.leanote.com) to import notes from evernote

**Comment by JeffMelton** [comment]
Before I opened this issue, that link was what I presume to have been a 404 (I don't read Chinese, and Google Translate doesn't do well with it either). Would you consider hosting those packages somewhere besides Baidu? Roll them into your repo, perhaps?

**Comment by lealife** [comment]
@JeffMelton Hi, you can download from https://sourceforge.net/projects/leanote-desktop-app/files/

**Comment by oktayaa** [comment]
@lealife  I am using the desktop app to export my leanote.com account data into my own hosted install. I have around 130 notes. When I do an export to Leanote or Evernote format I don't get an error. However the exported data is missing in most of them. When I check the text file I can see that the 

"content": "",

It only has the dates and title for these. Any idea?

**Comment by JeffMelton** [comment]
Cleaning up my ancient/abandoned issues. 😬
