### ISSUE TITLE
Linux 客户端版本的 Leanote 无法导入 Evernote 文件

### ISSUE THREAD

**Issue by woshijpf** [leanote/leanote#316]
我的 Linux 配置是 Ubuntu14.04 64 位版本，但是印象笔记的文件 .enex 无法导入到 leanote 的笔记本目录下啊？

**Comment by lealife** [comment]
有出错提示吗? 可以试着导入一篇简单的evernote笔记试试

**Comment by woshijpf** [comment]
![error](https://cloud.githubusercontent.com/assets/8475378/13495813/c0d790fe-e187-11e5-9780-93a11646c920.png)
我看了输出的日志，就是高亮部分的错误

**Comment by lealife** [comment]
这个错误很难定位, 如果你的evernote不私密的话, 可否发一份给我测试? lifephp@gmail.com 谢谢
你试着导入一篇简单的evernote试试?

**Comment by lealife** [comment]
你好, 建议参考 https://github.com/leanote/desktop-app/commit/1f8f59c3a125b52841d757862efa64fadea5fe2b 自己修改下, 已修复

**Comment by lealife** [comment]
https://github.com/leanote/desktop-app/blob/master/public/plugins/import_evernote/import.js
