### ISSUE TITLE
notebook panel taking full screen 

### ISSUE THREAD

**Issue by ddonindia** [leanote/leanote#317]
Hi Devs,

I just installed leanote on my linux box.
I am using nginx reverse proxy to host it on my website. I am able to login using my account but after login gui is not looking right.
Notebook panel is taking full screen and I am notable to create/view existing notes.
![error](https://cloud.githubusercontent.com/assets/16450468/13519407/ad44b6ea-e1fd-11e5-8c34-b187d4662ed1.png)

Following is nginx config:
```

server {
    listen 80;
    server_name abc.example.com;
    location / {
        proxy_pass http://192.168.1.2:9000/;
    }
}

```
Its working fine with Electron App.
Can you please help?

**Comment by ddonindia** [comment]
Its working fine if I select Chinese as ui language.
For English I am seeing following message in backend:

i18n.go:183: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present

**Comment by lealife** [comment]
It's so weird. Is there any error messages such as cannot load some css, js on web console ?

**Comment by lealife** [comment]
"i18n.go:183: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present" it doesn't matter, it just logger message

**Comment by ddonindia** [comment]
There is not error related to css,js in web console.
Its working fine with Chinese language.

**Comment by ddonindia** [comment]
@lealife any suggestion about this issue ?

**Comment by lealife** [comment]
@ddonindia is there any public url that direct to your leanote server ? I must have a look at it.

**Comment by ddonindia** [comment]
@lealife Its working fine on google chrome. Firefox is having that issue.
I thin I can live with chrome :).
Thanks alot for your help. Keep the good work :+1:
