### ISSUE TITLE
Man-on-the-Side Attack  ?

### ISSUE THREAD

**Issue by ddonindia** [leanote/leanote#318]
Why leanote accessing baidu.com/hm.js?

```
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?d0c988e37b452b3bf1220d45b30f2de2";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
```
As per [http://www.netresec.com/?page=Blog&month=2015-03&post=China%27s-Man-on-the-Side-Attack-on-GitHub](url)  this could be man on the side attack.

Can devs please explain ?

**Comment by ddonindia** [comment]
AutoShun reports it as **Malicious site**

[https://www.virustotal.com/en-gb/url/419a727d7d143a2f44ecb860684d005e81e412bec800b4a60a98a403e2024195/analysis/1457077578/](url)

**Comment by adareau** [comment]
I agree with ddonindia this is a matter of concern for me.

**Comment by ddonindia** [comment]
Till we get clarification from devs I suggest not to use leanote.

**Comment by lealife** [comment]
It's just baidu baidu statistics code, removed

**Comment by ddonindia** [comment]
Can you please explain what this code does?

**Comment by ddonindia** [comment]
Devs any reply to my previous comment or you are trying to hide something ?

**Comment by lealife** [comment]
The leanote.com has this code to do:
* Count PV
* Where user come from
* Users' ip

This code is comming from http://tongji.baidu.com/
Just like the Google analytics

**Comment by ddonindia** [comment]
Thanks @lealife  for clarification. 
Keep the good work !!!!!

**Comment by gerroon** [comment]
Can you remove the analytics now? Is it still embedded?

**Comment by ddonindia** [comment]
I also have stopped using.
