### ISSUE TITLE
run.sh 不应该往代码目录写入内容

### ISSUE THREAD

**Issue by BillLeecn** [leanote/leanote#325]
为了安全起见，部署的时候一般是以单独的用户运行 leanote, 并整个 leanote 的代码目录设置成仅 root 可写入。

可是 run.sh 却在代码目录中创建目录，建立符号连接什么的。这些东西可以直接在 tar 包中做好吧？

**Comment by lealife** [comment]
你好, 在tar包可能其它人下载后会有问题. 之前是在tar中建立了symlink, 但因他人下载解压后可能出现失效的情况, 所以在run.sh中建立链接.
