### ISSUE TITLE
[Bug] 升级会员后，网页上出现大量的???的乱码

### ISSUE THREAD

**Issue by yuki-zju** [leanote/leanote#326]
![qq 20160319133741](https://cloud.githubusercontent.com/assets/11500145/13896872/328ccfa0-edd8-11e5-82bb-068f8a0e09b7.png)

**Comment by lealife** [comment]
你好, 刷新下呢?

**Comment by yuki-zju** [comment]
还是这样的，用的火狐浏览器

**Comment by yuki-zju** [comment]
现在好了

**Comment by lealife** [comment]
谢谢!

**Comment by jonchin** [comment]
我的刷新完后还是？？？ 什么问题呢

**Comment by caopengfei** [comment]
我刚刚新安装的也满屏“？？？”
