### ISSUE TITLE
希望实现atom那样的多标签功能

### ISSUE THREAD

**Issue by strongduanmu** [leanote/leanote#346]
单标签页面操作很不方面，如果需要两个页面来回切换内容时，需要去目录树种找到文档，这种效率太低了。如果大神觉得不好实现的话，我觉得是不是可以在文档底部（点击添加标签那一行）位置做一行悬浮标签，用于记录当前打开过的页面，供用户切换。如果用户不需要再切换该页面时，可以选择双击关闭。希望大神考虑下。

**Comment by hlyang1992** [comment]
这个功能很重要啊, 特别是同时查看几个文档.
