### ISSUE TITLE
希望分享为博客的文件夹在博客中能够支持多级菜单

### ISSUE THREAD

**Issue by strongduanmu** [leanote/leanote#351]
例如我有一个文件夹叫Web前端知识，这个文件夹下有js、css两个子文件夹，可不可以分享Web前端知识这个文件夹时在博客中生成二级目录，一级目录为父文件夹，二级目录为子文件夹。要是实现就太棒了

**Comment by hellock** [comment]
Cannot agree more. It will be wonderful if blog themes of leanote support drop-down navigation menus.
