### ISSUE TITLE
更换site.url后，markdown的图片地址解析没有更新

### ISSUE THREAD

**Issue by myme5261314** [leanote/leanote#355]
例如我原本将leanote架设在xxx.com，然后在上面写了很多markdown的note，然后我换了网址，在app.conf中将site.url从xxx.com改为blog.xxx.com，然后会发现leanote客户端中图片显示正常，因为其内容为类似如下内容：

```
![jigsaw puzzle games](leanote://file/getImage?fileId=568dc965051c43797e000000)
```

而网页上却显示不正常，因为其仍被解析为类似如下内容

```
http://xxx.com/api/file/getImage?fileId=56ca7e3ddec3701ca96a8d49
```

而应该是

```
http://blog.xxx.com/api/file/getImage?fileId=56ca7e3ddec3701ca96a8d49
```

一个测试成功的解决办法是将所有笔记在leanote客户端中用markdown随便编辑加入一些内容，然后同步，然后图片就显示正常了。这里有一点，在网页note列表页面，还是会不更新解决结果导致图片链接失效。

> ![image](https://cloud.githubusercontent.com/assets/1814831/15235831/8a24cabc-18f1-11e6-9fb8-a2a7c747ccce.png)

还有之前自动生成的blog首页摘要，其中涉及到图片网址的部分，xxx.com也没有转换到blog.xxx.com，不过从blog首页点击进某个blog页面是正常显示的，在使用我描述的解决方法之后。

望跟进并修复。

**Comment by oliveagle** [comment]
+1

**Comment by lealife** [comment]
https://github.com/leanote/leanote/commit/a8dd5786247cd937545320b013fd44ee954095ac fixed
