### ISSUE TITLE
Adding Tinymce plugins

### ISSUE THREAD

**Issue by hydrogencn** [leanote/leanote#379]
Hi, first I want to say that leanote is extremely useful and I love it.

I did notice that the demo at [https://leanote.com/note](https://leanote.com/note) has a mind map tool (the light bulb to the right of the  insert/edit image button) in the tinymce editor. I just got the latest binary for linux (running Ubuntu 15.10 64 bit) and that feature isn't in there.

I combed through Tinymce documentation and leanote documentation looking for way I can do this but could not find a way.

So my question is: Is there a way to add this plugin, and possibly other plugins to the editor with my current installation?

Thank you

**Comment by lealife** [comment]
Hi, the mind map plugin isn’t the part of Leanote open source. you can find the Open source Mind map onhttps://github.com/fex-team/kityminder


Original Message
Sender:Robnotifications@github.com
Recipient:leanote/leanoteleanote@noreply.github.com
Date:星期四, 6月 23, 2016 09:12
Subject:[leanote/leanote] Adding Tinymce plugins (#379)


Hi, first I want to say that leanote is extremely useful and I love it.
I did notice that the demo at https://leanote.com/note has a mind map tool (the light bulb to the right of the insert/edit image button) in the tinymce editor. I just got the latest binary for linux (running Ubuntu 15.10 64 bit) and that feature isn't in there.
I combed through Tinymce documentation and leanote documentation looking for way I can do this but could not find a way.
So my question is: Is there a way to add this plugin, and possibly other plugins to the editor with my current installation?
Thank you

**Comment by hydrogencn** [comment]
Is it possible to get this in the open source version? I've been reading the documentation for kityminder, but there isn't much there.

**Comment by lealife** [comment]
Yes, it can be open source. But it may need a little longer time to do it.


Original Message
Sender:Robnotifications@github.com
Recipient:leanote/leanoteleanote@noreply.github.com
Cc:lifelifephp@gmail.com; Commentcomment@noreply.github.com
Date:星期五, 6月 24, 2016 05:26
Subject:Re: [leanote/leanote] Adding Tinymce plugins (#379)


Is it possible to get this in the open source version? I've been reading the documentation for kityminder, but there isn't much there.

**Comment by hydrogencn** [comment]
Okay, thank you for pointing me in the right direction
