### ISSUE TITLE
部署leanote到个人linux,使用公网ip地址访问，页面跳转出现localhost

### ISSUE THREAD

**Issue by jasonmg** [leanote/leanote#397]
当我部署leanote到我个人linux服务器，里面一些按钮充满了_localhost_跳转，比如在个人页面点击**我的博客** 转向URL: [http://localhost:9000/blog]，正确的应该是 http://linux ip:9000/blog。

**Comment by terryding77** [comment]
修改`leanote/conf/app.conf` 中的 **site.url**参数 改成 **http://你的ip:9000** 试试

**Comment by jasonmg** [comment]
great, thanks.
