### ISSUE TITLE
Go Compilation Error with go 1.7

### ISSUE THREAD

**Issue by Xunius** [leanote/leanote#401]
Hi developer,

Thanks for the good work put into leanote.

There seems to be some issues with the new go 1.7 version. Following up the source installation instructions and opening a web session, I got a "Go Compilation Error". More messages show up in the server side:
```
ERROR 2016/08/17 00:05:31 build.go:101: # github.com/leanote/leanote/app/tmp
/home/user1/go/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value

ERROR 2016/08/17 00:05:31 build.go:298: Failed to parse build errors:
 # github.com/leanote/leanote/app/tmp
/home/user1/go/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
```

No issues with the 1.6.3 version of go.

**Comment by lealife** [comment]
Leanote use revel 0.12 before, revel 0.13 has fixed this issue. Please upgrade revel to 0.13.
```
go get -u github.com/revel/cmd/revel
```
