### ISSUE TITLE
翻译问题，可长点儿心吧

### ISSUE THREAD

**Issue by JackieMium** [leanote/leanote#407]
注册使用的时候还是0.5.1,现在已经是2.1版了。
闲话不多说，我在Linux x86_64下的binary包一打开，英语环境，这翻译我直接跪了：

![2016-08-23-09 27 59_550x161_by_scrot](https://cloud.githubusercontent.com/assets/12944832/17877316/e40f63c0-6914-11e6-92c9-56869a2d09ab.png)

有幸有国际友人试用的话，看到这样的英语估计可能直接弃了吧.....

**Comment by lealife** [comment]
欢迎提交Pull request

**Comment by JackieMium** [comment]
@lealife  不会 （逃

**Comment by lealife** [comment]
帮忙, 你发现了这个问题, 肯定可以解决的

**Comment by JackieMium** [comment]
@lealife 我不是程序猿，Pull request不会，GitHub只会git clone一个命令

**Comment by lealife** [comment]
你把你的翻译贴到这, 会有朋友提交的, 麻烦了

**Comment by zhang-yuan** [comment]
不知道翻译的合不合胃口……

`Sorry, you can't add notes here, please choose a notebook first`

**Comment by lealife** [comment]
谢谢, 已合并

**Comment by JackieMium** [comment]
嗯，这样翻译就行。
