### ISSUE TITLE
本地开发环境打包后,修改的内容没生效

### ISSUE THREAD

**Issue by ystyle** [leanote/leanote#416]
用开发模式运行是成功的. `revel run github.com/leanote/leanote dev 9000`

开发环境是windows 10 x64, go 1.7

但打包后之前修改的内容不见了: 
1. 修改了一个api接口
2. 在git-bash 上运行, `.bin/release.sh`
3. 把生成的`leanote-windows-amd64.exe`替换 二进制安装包对应的文件 
3. `run.bat` 启动本地搭建的服务器,访问对应接口, 内容还是没修改前的

> 第二步`go build -o leanote-window-amd64.exe ./app/tmp` 生成的结果同上

求详细的编译方法! 

注: 

开发环境的搭建文档已经不见了

https://github.com/leanote/leanote/wiki/leanote开发版详细安装教程

**Comment by lealife** [comment]
开发版直接用dev运行就好了, 没必要打包. 打包就是运行bin/release.sh, 生成所有环境的Leanote

**Comment by lealife** [comment]
https://github.com/leanote/leanote/wiki

**Comment by ystyle** [comment]
可是我要生成linux的包, 替换正式环境里的啊, 改了都不生效......

**Comment by lealife** [comment]
修改后有没有运行revel run ...呢?

**Comment by lealife** [comment]
修改后运行 revel run github.com/leanote/leanote dev 9000, 让revel生成相应的main.go, 再运行 bin/release.sh

**Comment by ystyle** [comment]
谢谢, 可以了
