### ISSUE TITLE
android端调用/note/addNote 添加笔记，返回值不对额

### ISSUE THREAD

**Issue by xingstarx** [leanote/leanote#418]

**Comment by xingstarx** [comment]
<img width="1206" alt="leanote-android-2016-09-03-001" src="https://cloud.githubusercontent.com/assets/8245264/18222180/ff43c99c-71c0-11e6-8a34-636f2803c8b7.png">

**Comment by xingstarx** [comment]
![leanote-android-2016-09-03-002](https://cloud.githubusercontent.com/assets/8245264/18223034/0b936510-71dd-11e6-8328-f71ad4406926.png)

返回的content竟然mei没有值，是服务器的bug吗

**Comment by lealife** [comment]
内容不会返回


Original Message
Sender:xxxnotifications@github.com
Recipient:leanote/leanoteleanote@noreply.github.com
Date:星期六, 9月 3, 2016 13:48
Subject:Re: [leanote/leanote] android端调用/note/addNote 添加笔记，返回值不对额 (#418)


返回的content竟然mei没有值，是服务器的bug吗

**Comment by xingstarx** [comment]
是的，我明白了，服务器的返回content内容太大也不好。
