### ISSUE TITLE
图片链接不对

### ISSUE THREAD

**Issue by luyunfei** [leanote/leanote#423]
leanote 粘贴图片/文件后，会生成一个图片链接file://...，但是问题来了，我们知道leanote导出的pdf会很大很大很大，所以我需要把markdown内容粘贴到mou中，用mou导出，可是图片链接不对哦，怎么破？

**Comment by mybuddy** [comment]
这个链接应该是私有的吧，只有leanote自己可以读取

**Comment by lealife** [comment]
@mybuddy 对
在客户端, 图片的链接都会变成 leanote://的形式, 是leanote的协议
