### ISSUE TITLE
谷歌浏览器，输入问题

### ISSUE THREAD

**Issue by QQ-ing** [leanote/leanote#427]
谷歌浏览器昨天更新了新版本，53.0.2785.116 m (64-bit)
然后发现输入有问题。
问题：我在输入  “首先” 时，结果是 "shouxian" 。然后我再随便输入一个东西，就会出现 ”shouxian首先“。
输入法QQ输入法纯净版，在谷歌浏览器上，切换了微软的输入法还是这样。
切换浏览器，火狐，问题解决。希望可以尽快改一下 ：）
最后祝leanote越来越好！

**Comment by X-Mars** [comment]
我也一样

**Comment by gunuo** [comment]
我的也是一样，leanote上的用户名为peku2012@163.com，一开始以为是我的电脑问题，看来是软件问题，还请尽快解决吧。

**Comment by lealife** [comment]
https://github.com/ajaxorg/ace/issues/3099

**Comment by lealife** [comment]
正在修复

**Comment by lealife** [comment]
https://github.com/leanote/leanote/commit/15d8ebdc0fea664abf746d7c1438443d9d5ccf0f
