### ISSUE TITLE
客户端无法登录自建服务；网页端无法导出PDF

### ISSUE THREAD

**Issue by mo-han** [leanote/leanote#434]
客户端：
- Windows 10 64位 LTSB 2016
- leanote-desktop-windows-x64-v2.1

服务端：
- VPS: Ubuntu 16.04 x64
- leanote-linux-amd64 v2.0 二进制版
- MongoDB v3.2.10
- supervisor v3.2.0
- nginx/1.10.0 (Ubuntu)
- 强制HTTPS / 自签名证书

故障、现象：
- 自建服务的网页可以登录，功能和显示均正常（除了PDF导出功能）
- 桌面客户端无法登录自建服务，提示用户名（邮箱）或密码错误，已经多次核对检查输入
- 自建服务网页端无法导出PDF，点击“导出PDF”浏览器标签页有活动，但页面静止，最后也没有输出PDF文件
- 服务端已经安装`wkhtmltopdf`，我用百度网页测试过，可以输出PDF，除了中文字体其他均完好

很严重的问题，也不是个例，希望尽快分析问题。
如果需要配置文件或日志，烦请告知相关信息，我不知道要提供哪些。

**Comment by RMOTD** [comment]
客户端：服务器地址后加上端口号

PDF：需要网页登录admin账户，进入后台管理，添加htmltopdf所在路径。

**Comment by lealife** [comment]
"桌面客户端无法登录自建服务，提示用户名（邮箱）或密码错误，已经多次核对检查输入" 自建地址输入的是什么? 有没有http://前缀?

**Comment by lealife** [comment]
PDF导出需要在后台设置wkhtmltopdf路径

**Comment by mo-han** [comment]
@lealife
http://的正常登录，https://的失败。我用的自签名SSL证书。
wkhtml2pdf路径已经正确设置，实际上在服务器中可以看到已经成功转换的PDF文件保存在`file`目录下，但是网页不给我下载。

**Comment by w15971597** [comment]
@mo-han 看下日志，是不是mongod没启动，mongod没启动是会报密码错误
