### ISSUE TITLE
性能很差，有时打开网页需要一分多钟

### ISSUE THREAD

**Issue by ysnicelife** [leanote/leanote#445]
不论是打开主页 还是分类的笔记中图片过多（其实也就10张左右），就开始出现性能问题，打开的很慢，有时打不到

**Comment by yifanes** [comment]
加载图片就是简单的http请求，和leanote的性能无关，可以查看下图片加载耗时来确定图片所在服务器网络问题

**Comment by wdy1184** [comment]
看着像是服务器没有对文件进行压缩导致的，图片都是原封不动的加载

**Comment by ysnicelife** [comment]
图片都是粘贴在笔记中的，不是外链，即使这样图片也不在蚂蚁服务器上吗？

**Comment by ysnicelife** [comment]
而且也不仅仅是打开有图片的笔记慢，点击登录后，也要好久才进来，我在公司和家里都这样，不是网络问题

**Comment by lealife** [comment]
leanote.com 已使用七牛图片, 以后速度会好很多
