### ISSUE TITLE
【存在错误】app.conf更改ip地址或端口后图片无法加载

### ISSUE THREAD

**Issue by RMOTD** [leanote/leanote#455]
http.port=
site.url=

这两项的端口变更后，笔记中的图片就变成了一个空白链接了，再改回原端口并重启，才能正确显示。

另外，单独备份恢复到另一台不同ip的主机，只改变ip不改变端口,（图片以及附件文件夹，全部原封不动，只修改ip）也会出现同样问题。

![2016-11-05 6 41 26](https://cloud.githubusercontent.com/assets/22410135/20029489/405611f8-a388-11e6-92cd-ce214107c162.png)

**Comment by lealife** [comment]
https://github.com/leanote/leanote/commit/a8dd5786247cd937545320b013fd44ee954095ac
