### ISSUE TITLE
[BUG]Tag删除后，无法以同样的字段新建Tag

### ISSUE THREAD

**Issue by houxg** [leanote/leanote#461]
1. 新建Tag, 名为"tag10"
2. 删除该Tag
3. 新建Tag, 名为"tag10", 返回的Tag.IsDeleted = true

**Comment by helloxz** [comment]
测试标签似乎的确存在BUG，当我添加一个abc123的标签，然后删除，再重新添加abc123，结果左侧标签不会再显示abc123了，如下截图。请官方测试
___
![](https://img.bsdev.cn/uploads/1612/130517345615.png)

**Comment by helloxz** [comment]
多次刷新，左侧依然没有出现abc123这个标签。并且测试通过搜索abc123也不会显示文章。
