### ISSUE TITLE
博文打赏

### ISSUE THREAD

**Issue by fangjidezhu** [leanote/leanote#464]
目前好几个博客平台都集成了打赏功能，读者为帮助了自己或者欣赏的内容进行付费，作者的付出得到了回报，这样的互动是更好的运营方式，请考虑一下这个建议吧

**Comment by helloxz** [comment]
这个功能其实不难，你自己编辑你的博客主题在适当的地方加个打赏二维码即可。

**Comment by lealife** [comment]
不计划支持
