### ISSUE TITLE
建议增加"为知笔记"导入功能.

### ISSUE THREAD

**Issue by AL0n4k** [leanote/leanote#477]
如题. 将为知笔记里的内容导入到此笔记中.

**Comment by h2y** [comment]
同求，或者说有什么方法添加 html 格式的文件成为笔记？

**Comment by houxg** [comment]
最新版桌面端已经支持v2.2.1

**Comment by fashioncj** [comment]
导入好像有点问题，怀疑是标题空格或者其他的。在批量导入的时候会出现只导入一部分。没找到具体的代码实现。

**Comment by h2y** [comment]
@fashioncj 
@houxg 

我下载了 2.2.1，但是没有找到导入的方法，求帮助 >.<

**Comment by ssjlz4670** [comment]
@h2y 现在的做法是导出为html,然后导入,我估计！同为为知笔记转过来的

**Comment by carlleton** [comment]
我试过这样可以导入成功，为知笔记导出html，leanote最新版本导入html：
PS：
1.每个目录导出再导入
2.为知笔记导出的时候选择模板generic，选上“套用模板”，这个模板能自动的增加html和body标签，符合leanote导入的规范
3.标题以特殊符号开头的leanote导入不了，最好在wiz里边把以特殊符号开头的改掉再弄

**Comment by lealife** [comment]
@h2y 右键笔记本, 导入 -> 导入Html/为知

**Comment by h2y** [comment]
@lealife 

谢谢，发现一个问题：

为之有的导出 html 是不带 <html><body> 的，这样的文件没法用 leanote 导入，提示不是 html 文件。

手动添加 `<html><body>` 和 `</body></html>` 在开始末尾之后，就可以正常识别并导入了。

**Comment by lealife** [comment]
@h2y 是的Leanote桌面端导入HTML是解析Body里的内容, 我发现为知导出有些有Body, 有些没有Body, 不规范

**Comment by txb2d** [comment]
@carlleton你说的这这种办法我试了，还是不行，点击导入直接没反应！这是我自己从为知导出的数据，大家可以测试下[测试数据](http://pc.micloud.site:81/index.php?share/file&user=1&sid=hgJ7vqU4)

**Comment by lealife** [comment]
Confirmed

**Comment by lealife** [comment]
https://github.com/leanote/desktop-app/commit/f1d5f87e48ddc9ce4ec2a8042ecfff8248836436
