### ISSUE TITLE
Mac 端 md 预览效果未能同步至 Web 端和博客

### ISSUE THREAD

**Issue by Aixtuz** [leanote/leanote#480]
**问题描述：**
1. Mac 端编辑 md 后保存、同步；
2. Web 端内容一致，但列表中预览效果仍为实际字符；
3. 此时博客首页预览，同样只显示实际字符;
4. Web 版重新编辑保存，博客刷新后预览正常;

**版本**
> Mac OS X v2.1
> leanote-linux-amd64.v2.2.bin.tar.gz

**Comment by timgogochen** [comment]
Linux 64Bit server， windows client also face this issue,

**Comment by lealife** [comment]
预览不同步, 实时解析

**Comment by timgogochen** [comment]
开发大拿上来了？围观！  不仅网页版不更新，博客也不更新。而且还有个BUG，客户端使用强制同步后，文章中的图片全丢了。丢了。。。

**Comment by lealife** [comment]
@timgogochen 你说的BUG不在这个issue讨论范围内, 请重新开一个issue, 一定要附上服务器&桌面端版本及操作步骤
