### ISSUE TITLE
自建服务, 如何修改管理员邮箱, 直接改 db 貌似不行

### ISSUE THREAD

**Issue by fengqi** [leanote/leanote#482]
直接改 users 表数据, 还是会往 admin@leanote.com 发送邮件, 然后被拒

还有普通用户如何修改

**Comment by lealife** [comment]
改db肯定是可以的

**Comment by fengqi** [comment]
我改 db 后, 在网页上看到生效了, 但是点击发送验证邮件的时候不是往看到的(修改后的)邮箱发, 还是发往 admin@leanote.com

**Comment by txb2d** [comment]
我也想知道，为什么要把邮箱固定！而不能修改！！！

**Comment by lealife** [comment]
邮箱就是ID, 试想一下, 如果你的密码被盗, 然后可以改邮箱. 你还有机会找回吗?

**Comment by fengqi** [comment]
密码被盗问题，发送一封邮件到旧邮箱不就行了。
admin 这个明确说了修改db不行

**Comment by lealife** [comment]
改DB肯定是可以的!!!!!!!!!!!!

**Comment by fengqi** [comment]
显示邮箱变了，但是还是往旧邮箱发邮件！
life <notifications@github.com>于2017年1月15日 周日12:45写道：

**Comment by lealife** [comment]
你怎么改的?

**Comment by lealife** [comment]
数据庫都改了, 理论上是Leanote是不知道旧邮箱的

**Comment by fengqi** [comment]
你也说理论上了，我是直接修改用户表
life <notifications@github.com>于2017年1月15日 周日12:48写道：

**Comment by lealife** [comment]
"显示邮箱变了，但是还是往旧邮箱发邮件" 你怎么知道它是往旧邮箱admin@leanote.com发的呢?

**Comment by fengqi** [comment]
看日志以及退件
life <notifications@github.com>于2017年1月15日 周日12:52写道：

**Comment by lealife** [comment]
你好,请有时间截图db的管理员用户
无法复现

**Comment by fengqi** [comment]
有时间再说吧，已经卸载，懒得再装
life <notifications@github.com>于2017年1月15日 周日13:07写道：

**Comment by lealife** [comment]
再次确定:
1. admin@leanote.com管理员邮箱可通过改数据库解决, `db.users.update({"Email" : "admin@leanote.com")}, {$set:{Email: 'xx@xx.com'}})`. 之后可以到找回密码界面输入改之后的邮箱即可. 如果接收不到邮件, 请确定后台管理的邮箱配置是否正确.
2. Leanote不会支持普通用户修改Email的功能, 实际上之前是支持的, 但考虑到安全原因. Email就是ID, 无法更改!

**Comment by iKira** [comment]
@lealife 数据库是通过哪个地址访问呢？一直没找到……
