### ISSUE TITLE
revel.go:301: GOPATH environment variable is not set. 

### ISSUE THREAD

**Issue by devotion987** [leanote/leanote#485]
leanote安装，mongo数据导入成功了，执行“go install github.com\\revel\\cmd\\revel”也没问题，但执行“revel run github.com\\leanote\\leanote”会报“revel.go:301: GOPATH environment variable is not set. ”，golang环境设置好的，这个问题怎么解决？求指教！

**Comment by lealife** [comment]
请执行 `echo $GOPATH` 看看

**Comment by devotion987** [comment]
已解决，go安装后会自定增加GOROOT变量，GOPATH需手动添加，两个变量有区别
