### ISSUE TITLE
三栏式布局很不喜欢

### ISSUE THREAD

**Issue by Xiang1993** [leanote/leanote#492]
感觉三栏式的布局很不爽, 空间不够大, 建议可以把最左侧一栏的隐藏, 另外, "文档导航"的那个功能放在右上角真的好丑, 如果能够做成Typora的那种 "show outline pannel"就完美了!

**Comment by txb2d** [comment]
三栏还不错啊！

**Comment by edward12699** [comment]
我挺喜欢栏目的布局

**Comment by lealife** [comment]
你好, 如果你说的是网页版, 最左可以隐藏. 你说的客户端, 请发布到desktop-app项目中
