### ISSUE TITLE
希望支持剪藏功能啊

### ISSUE THREAD

**Issue by xshrim** [leanote/leanote#493]
浏览器上剪藏网页内容应该是使用云笔记最常用的功能之一吧，其他的云笔记都有（印象和为知的剪藏都很好），蚂蚁云笔记为什么不支持呢，这个很重要啊，强烈建议支持这个！

**Comment by txb2d** [comment]
手动复制把，想要哪里copy哪里呀！

**Comment by xzhlksh** [comment]
说实话，剪藏网页还真没几家做，云笔记里好像也就为知和大象做得相对好点（实际还是稀烂）。感觉这个并不是高优先级，而且优雅实现的确太难

**Comment by lealife** [comment]
近期不会实现, 剪藏只会增加无用的知识!!!!!!!!!!!!!!!

**Comment by hongrunhui** [comment]
不支持lealife的观点，为什么会增加无用的知识？我用剪藏功能收集了很多网页，包括一些问题的解决方案，每当我再次遇到相同问题后，我只要在剪藏中搜索一下，就可以看到我想要的解决方案。而且我会不定时的去看剪藏的东西。有空的时候我会去总结剪藏中的某一篇文章，用自己的语言写出来，这样会增加无用的知识吗？现在印象笔记吸引我的就这一点，不然我早就抛弃印象笔记了，相信很多用户也是，当然我也用leanote，我主要用你们的markdown功能来记录自己的写的一些总结和心得，所以，还是希望大大们开始开发剪藏功能，我敢保证，这是增加你们用户量的一个绝佳途径，并且还可以收费。

**Comment by hongrunhui** [comment]
对了，我还建议你们能够改进笔记的预览功能，希望能在原来的基础上对预览的样式字体什么进行更改，譬如我每周总结要给别人看，那么我放在投影屏幕上可以显示比较好看字体以及大小，会让人舒服很多，印象笔记的预览功能就做的很好，但是还可以做得更好，希望你们能斟酌一下。
