### ISSUE TITLE
强烈建议文案增加公网mongodb必须设置密码等安全信息，最近 “赎金事件”频发，中招ing

### ISSUE THREAD

**Issue by carlleton** [leanote/leanote#494]
如题，前两天中招，库被删，幸好有备份有补救
另外建议增加备份自动发送邮箱的功能

**Comment by mfy** [comment]
![77vgjeiu_4 f bl eozz uu](https://cloud.githubusercontent.com/assets/1912554/21759558/01f23d58-d680-11e6-8c5b-3dfd33765c76.png)
I am a victim...

**Comment by orvice** [comment]
从源安装就ok

**Comment by itsjoke** [comment]
有安全意识的人自己就会知道操作，没意识的人提醒了也不一定会做。

**Comment by lealife** [comment]
所有安装文档已添加

**Comment by xingstarx** [comment]
安全意识很重要
