### ISSUE TITLE
Problem syncing images between web and apps

### ISSUE THREAD

**Issue by pquan** [leanote/leanote#504]
I am experiencing problems with image sync in notes.

If an image is dropped in the web-app on a note, and later synced to windows/mac/linux it will not appear on all platforms. The image is visible in web, but shows empty box in the apps.

When an image is inserted in a note from one PC, it is visible in the web, but cannot be synced in another app on another computer. The note shows empty box.

Further, if I force full sync on the original app (not web, but mac/windos/linux app) that inserted the image in the beginning, the image will be deleted and becomes not visible (empty box).

I'm running leanote 2.2.2 and apps 2.2.2 and 2.2.3. Same issues everywhere.

**Comment by lealife** [comment]
Hi, Please check that the `site.url` on 'conf/app.conf' is same as the `Host` which set on desktop app.

**Comment by lealife** [comment]
https://github.com/leanote/leanote/wiki/Leanote-QA-English#cannot-sync-images

**Comment by txb2d** [comment]
@lealife 别只回外国友人得问题，也想办法解决下中国同胞得问题，不然下次我也用英文发表问题了！

**Comment by pquan** [comment]
Thank you @lealife. I had foreseen that part of the FAQ.

Dear @txb2d, I'd suggest you start writing in english, as I'd suggest the same for the whole project. It makes it much easier to get other people and developers involved if you write in a common language that all can understand. 

I'll mark this as resolved now (non issue). Thank you.
