### ISSUE TITLE
MAC客户端无法连接自建服务

### ISSUE THREAD

**Issue by terryzwt** [leanote/leanote#505]
多谢这么优秀的开源项目！
但是使用过程中遇到点问题，就是使用MAC客户端无法连接自建服务，
显示“用户名或密码错误”。
但是同样的用户名和密码可以在网页端登录。

**Comment by lealife** [comment]
很可能原因是:
1. 自建服务地址是否填定正确, 地址一定要是http://a.com, 或 http://a.com:9001的形式
2. 桌面端不支持自建https

**Comment by terryzwt** [comment]
果然放到公网上，使用域名形式就好了，
之前本地测试，写的是http://localhost:9000，一直有问题。
多谢解答！！


另外做了个docker composer，目前凑活可用。不知道有没有兴趣把我加到docker维护的maintainer里面?
https://github.com/terryzwt/leanote
个人维护一些php的开源项目，有一定的经验。
