### ISSUE TITLE
BUG：tag链接中的空格处理

### ISSUE THREAD

**Issue by gaunthan** [leanote/leanote#513]
文章、或主页概览生成的tag，有链接处理问题。目前发现tag名称中的空格会被'+'代替，使得tag链接无法使用。

如[这篇文章](http://leanote.leanote.com/tag/love%20writting)的tag入口，生成的链接为：http://leanote.leanote.com/tag/love+writting。

而在tag页生成的链接，则没有这个问题。

**Comment by lealife** [comment]
Confirmed. Thanks

**Comment by gaunthan** [comment]
原先有作转义处理，但链接失效，估计是后台那边还没有改过来。

现在去掉了 url.QueryEscape() 转义处理，虽然空格、小于号等会被 template.HTML() 转义处理，但是如果链接名称中包含斜杠，则依旧有错。望尽早修复。
@lealife
