### ISSUE TITLE
leanote-windows-amd64-v2.2.2.bin.tar.gz  cant export pdf (no respond). Wx is ok in cmd

### ISSUE THREAD

**Issue by daoye2011** [leanote/leanote#514]
wx  path D:\Programs\wkhtmltopdf\bin\wkhtmltopdf

**Comment by daoye2011** [comment]
晕win下居然用linux命令

**Comment by daoye2011** [comment]
估计都没人测试win

**Comment by lealife** [comment]
已确定

**Comment by Biggulu** [comment]
请问windows中使用v2.3导出pdf的路径该如何填写?没有查到相关资料,按照windows下的路径填写无效,cmd中测试wx ok.还有一个问题在linux下使用wx导出的PDF文档都是深色背景

**Comment by lealife** [comment]
2.3仍没解决, 请使用桌面客户端导出PDF

**Comment by KennyDiff** [comment]
2.4这个问题还是没解决吗？ 应该怎么写？ windows 下 路径～

**Comment by lealife** [comment]
2.5 fixed
