### ISSUE TITLE
Bug about Mathajax

### ISSUE THREAD

**Issue by zeakey** [leanote/leanote#515]
Hi dear ALL,
I recently find a bug on math equations layout when I publish my note as a blog, but the math equations present well in the note preview.

 I don't how to upload an image here on Github issue so I give my blog's link here <http://leanote.com/s/587cce4a0da9e04e8c000000>, the equation is at bottom of the page.

**Comment by lealife** [comment]
Confirmed. http://blog.leanote.com/post/zeakey@126.com/LDL%E5%AE%9E%E9%AA%8C is ok

**Comment by lealife** [comment]
Fixed

**Comment by zeakey** [comment]
@lealife OK, thanks a lot for your quick response.
