### ISSUE TITLE
Search bar of blog doesn't make any sense on Mozilla Firefox 50.1.0

### ISSUE THREAD

**Issue by gaunthan** [leanote/leanote#516]
I tested search bar of blog on Chrome and Firefox,  and found it doesn't work on Mozilla Firefox 50.1.0.
The following message was printed by browser inspector:

> 
> Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery-1.9.0.min.js:2:8283
>
> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!     gaunthan.leanote.com

I have no idea of whether the above message is related to the problem I mentioned.So I am just looking for help to solve the problem.

Any advise or solution, leave it here, thanks! :)

**Comment by lealife** [comment]
Confirmed, thanks
