### ISSUE TITLE
Tag删除不了

### ISSUE THREAD

**Issue by AnnPeter** [leanote/leanote#519]
不小心添加了一个比较奇怪的tag，很长，删除不掉，试了下正常的tag是可以删除掉的，下面附上删不掉tag的内容。

`* SpringBoot修改默认启动端口: 设置虚拟机参数-Dserver.port=809                 java -jar -Dserver.port=8090  XXX-1.0-SNAPSHOT.jar * 事务不会滚原因     * Mysql数据库引擎一定要为innodb， 其它引擎不支持事务     * 抛出的异常一定要是Runtime Exception（当然设置代理的时候 可以指定回滚条件）     * 事务方法内部调用，内部调用不会经过代理对象进行调用，而是直接本对象进行了调用(不要使用this.xxx()进行调用， 使用xxxServic.xxx()进行调用，因为xxxService是经过spring代理来的。也可以使用getBean，获得自己在spring容器中的对象)     * 代理是否生成，配置是否正确     * spring的controller多重载入。在父容器applicationContext（applicationContext.xml）中载入了service、dao等组件的时候，子容器载入Controller（dispatcher-servlet.xml）时由于多扫描了包，并且在Controller在载入的时候service、dao等组件还没有就绪，子容器就会创建自己的service、dao等 * 初始化过程     * ClassPathXMLApplicationContext(“xxx.xml”)     * 初始化ApplicationContext，BeanFactory和ResourceLoader`

**Comment by lealife** [comment]
已确定
