### ISSUE TITLE
bug类似物 iPad上

### ISSUE THREAD

**Issue by yukihiratype2** [leanote/leanote#52]
markerdown，拖动编辑框，预览框变小。拖动预览框，编辑框变小。

**Comment by yukihiratype2** [comment]
![image](https://cloud.githubusercontent.com/assets/10401396/5613613/0438c63c-9522-11e4-8791-bfa772ccd9d8.jpg)

**Comment by yukihiratype2** [comment]
![image](https://cloud.githubusercontent.com/assets/10401396/5613631/3dd79b8e-9522-11e4-929e-08b8b91d124f.jpg)

**Comment by lealife** [comment]
请确认现在还有这个问题吗? 谢谢!

**Comment by yukihiratype2** [comment]
没有啦
