### ISSUE TITLE
服务器数据全部丢失, 本地的还在的情况能还原吗? 

### ISSUE THREAD

**Issue by ystyle** [leanote/leanote#520]
服务器数据全部丢失, 本地的还在的情况能还原吗?

**Comment by ystyle** [comment]
app.conf 文件还在.

**Comment by lealife** [comment]
你好, 可以先将桌面端数据全备份成.leanote文件, 然后在服务端新建账户, 桌面端用新账户登陆. 导入Leanote笔记. 再同步到服务端

**Comment by ystyle** [comment]
没有整个帐号导出的功能吗? 分类太多了.

**Comment by lealife** [comment]
只能分笔记本导出了, 没有整个导出的选项
