### ISSUE TITLE
Leanote部署报错

### ISSUE THREAD

**Issue by YoungCabbage** [leanote/leanote#522]
按照  wiki “二进制版详细安装教程 Mac and Linux ”安装，结果到启动 mongod 一直报错，，如下： [root@localhost user1]# mongod --dbpath /home/user1/data -bash: /home/user1/mongodb-linux-x86_64-rhel62-3.4.1/bin/mongod: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory 
我使用的VPS 是搬瓦工，系统是 centos 6 32 位  
1.google 了一下，有人说是因为 64 位系统中安装了 32 位程序。可是我这个明明是 32 位系统呀。 
2.我在 mongodb.org 找到的是“ mongodb-linux-x86_64-rhel62-3.4.1.tgz;”，是不是因为版本的问题？
3.难道目前mongodb只支持64位的？

**Comment by ddyllen-z** [comment]
你的系统32位？下载的64位程序，运行不了。

**Comment by YoungCabbage** [comment]
mongodb的32位的吗？我在[下载中心](https://www.mongodb.com/download-center?jmp=nav)找了半天，全是64位。能帮忙看下吗？

**Comment by ddyllen-z** [comment]
@YoungCabbage 我也没看见有64位的，那就是不支持32位了吧！你把系统换成64位的呀！
