### ISSUE TITLE
不停地弹窗

### ISSUE THREAD

**Issue by TryndamereStark** [leanote/leanote#528]
我把ip改成自建服务器，结果现在不停地弹窗，标题“leanote”，内容"33"；现在旧的账户里的东西能不能找回来？ 

> http://ok6con611.bkt.clouddn.com/%E6%97%A0%E6%A0%87%E9%A2%98.png

**Comment by lealife** [comment]
"ip改成自建服务器", 是怎么改的?

**Comment by TryndamereStark** [comment]
切换账户

**Comment by TryndamereStark** [comment]
原来是用官方的服务器，后来我用自己的vps搭了一个leanote服务器，然后客户端相应的ip改成自己服务器的ip

**Comment by TryndamereStark** [comment]
![image](https://cloud.githubusercontent.com/assets/11473283/22181623/b5bc5c2a-e0ca-11e6-84b6-8864c21e3e83.png)

**Comment by TryndamereStark** [comment]
这个版本  leanote-desktop-windows-x64-v2.1

**Comment by lealife** [comment]
客户端相应的ip改成自己服务器的ip.
你把leanote.com 的ip改成了其它的?

**Comment by TryndamereStark** [comment]
没修改任何源码，只是使用了类似chrome插件里的这个功能
![image](https://cloud.githubusercontent.com/assets/11473283/22181720/83c7d08a-e0cc-11e6-8933-9c82e852442e.png)我输入的是自己的服务器ip+9000端口

**Comment by lealife** [comment]
看你的截图是你的桌面端弹窗
Chrome插件和你的桌面端没有关系的

**Comment by TryndamereStark** [comment]
我只是打个比方。。。

**Comment by lealife** [comment]
我现在已经不清楚你做了什么操作导致了不断弹窗. 请描述清楚!

**Comment by TryndamereStark** [comment]
待会我重新下一个包看看能不能重现这个问题

**Comment by TryndamereStark** [comment]
现在用的是官网最新的 leanote-desktop-windows-x64-v2.2.3可以登录自建服务器了，但是官方服务器登录不了了 #529

**Comment by lealife** [comment]
以后提issue要说明问题来由!
