### ISSUE TITLE
无法登录账户

### ISSUE THREAD

**Issue by TryndamereStark** [leanote/leanote#529]
用的是官方服务器，那个圆圈一直在转![image](https://cloud.githubusercontent.com/assets/11473283/22181901/c0eef146-e0d1-11e6-9b4a-0f6863a3c8ea.png)

**Comment by TryndamereStark** [comment]
好吧，好像是因为试用期结束了，这里应该提示一下试用期结束 @lealife

**Comment by TryndamereStark** [comment]
1月16日到现在还没30天吧？？？！！！![image](https://cloud.githubusercontent.com/assets/11473283/22181991/7c2db83c-e0d4-11e6-86eb-2c40b989ccd6.png)

**Comment by txb2d** [comment]
我看你怎么死的！

**Comment by lealife** [comment]
@TryndamereStark 你好, 请提供你的账号名给leanote@leanote.com. Github不是leanote.com服务的讨论地, 而是Leanote开源的社区.

**Comment by lealife** [comment]
@txb2d 你有什么资格谈论Leanote?
