### ISSUE TITLE
[Help Wanted] 如何注销第三方帐号？

### ISSUE THREAD

**Issue by gaunthan** [leanote/leanote#531]
由于使用过QQ、Github等第三方帐号登录Leanote，导致无法将这些第三方帐号绑定到Leanote帐号。

请问是否有注销帐号的方法，以便将这些第三方帐号绑定至特定Leanote帐号？

**Comment by lealife** [comment]
个人中心有第三方账户管理, 解绑即可

**Comment by gaunthan** [comment]
lealife，可能我没讲清楚。

我指的是用第三方帐号首次登录leanote，例如用QQ，那么登入之后，后台就会留下了一个帐号。这个帐号并没有关联到一个leanote帐号，因此在个人中心是无法解绑QQ这个关系的，因为主帐号是QQ而不是leanote帐号。

可能这里有个“人不可能举起自己”这样的设定。

**Comment by lealife** [comment]
你好, 对于这种情况, 你需要在Leanote个人中心先添加一个 Leanote账户, 才能解绑

**Comment by gaunthan** [comment]
You are using the 3th account to login Leanote, you can create a Leanote account too. 
After you create Leanote account, you can use the account and the 3th account to login Leanote.

第三方帐号似乎只提供了**新建**Leanote帐号功能？或者是我没找到入口？

**Comment by lealife** [comment]
新建Leanote账户, 表示建一个账户和该第三方账户关联, 创建后可以用任何一个登录.

**Comment by gaunthan** [comment]
您是说为这个第三方帐号新建一个Leanote账号，然后在这个账号的中心设置里把第三方帐号解绑吗？

这有点溜啊！ :-D

**Comment by lealife** [comment]
对的

**Comment by MrFive5555** [comment]
相同的问题,比如我用微信登录过一次,谷歌账号登陆过一次,微信和谷歌的账号就没有办法关联了
