### ISSUE TITLE
图片不能上传

### ISSUE THREAD

**Issue by yarcowang** [leanote/leanote#532]
小哥, 我建了个自用, 感觉不错. (我准备从 evernote 迁过来了...)

二进制版的:
地址: https://notes.bbish.net
用户名: demo
密码: demodemo

但无法上传图片, 不知道啥原因? (错误信息里 也没看到啥信息...大概是啥权限问题, 我只设置了 `public/upload` 777)

```
{"Ok":false,"Code":0,"Msg":"error","Id":"","List":null,"Item":null}
```

**Comment by yarcowang** [comment]
另, 怎么设置 端口号 只绑定 127.0.0.1 ? 比如, 我只想开放80的virtualhost

**Comment by yarcowang** [comment]
上传头像可以阿...

**Comment by lealife** [comment]
笔记内的图片不放到public下, 放在Leanote根目录下的files目录下, 请设置权限
