### ISSUE TITLE
v2.4版本会发现有些笔记无法显示出来

### ISSUE THREAD

**Issue by shitfSign** [leanote/leanote#551]
leanote-windows-amd64-v2.4.bin.tar.gz

**Comment by lealife** [comment]
可以与前一版界面对比下吗?
控制台是否有错误信息?
强制刷新是否能解决?

**Comment by lealife** [comment]
如果提问者不再提供后续的信息, 该issue就会关闭!

**Comment by shitfSign** [comment]
不好意思， 我重新试了一下，清空缓存，目前是没有看到问题。
