### ISSUE TITLE
Toggle preview keyboard shortcut

### ISSUE THREAD

**Issue by jonygli** [leanote/leanote#565]
is there a keyboard short to toggle preview?

**Comment by lealife** [comment]
command/ctrl + e

**Comment by jonygli** [comment]
**command/ctrl + e** is used to switch edit and read-only.

My question is for the way to minimize the preview. 
in editing, I don't need to display the preview as the screen is not big enough.

the best seems to loop 'edit markdown only', 'preview only' and 'half edit/preview'
