### ISSUE TITLE
希望支持html源码编辑，但ace编辑器的按钮不起作用

### ISSUE THREAD

**Issue by ashfinal** [leanote/leanote#57]
希望支持html源码编辑功能，但ace编辑器的按钮不起作用
![ace toggle](https://cloud.githubusercontent.com/assets/6827900/5788768/3fb5221c-9e84-11e4-88be-75b6051100cb.png)
源码编辑在网页编辑器不好用或者markdown语法不够强大的情况下，会非常有用。

**Comment by leanote** [comment]
这个按钮的作用是只在普通的pre与ace editor相互切换

**Comment by leanote** [comment]
源码直接我们在考虑中, 其实之前没有ace编辑器的时候支持源码, 但ace添加之后会产生大量的其它代码
