### ISSUE TITLE
使用mongo数据迁移时,图片和附件无法显示

### ISSUE THREAD

**Issue by FansinZhao** [leanote/leanote#574]
使用环境:Ubuntu下docker
版本:mongo最新docker镜像,leanote最新版本
问题描述:使用mongo 导入数据无法显示图片和附件,其他内容正常.
希望解答一下.

**Comment by lealife** [comment]
附件和图片不存在mongodb中, 请将leanote下的public/upload, files目录也迁移到新Leanote中

**Comment by Jeff-Ren** [comment]
@lealife 感谢，解决一个图片无法加载的问题
