### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by xmu714** [leanote/leanote#579]
> 按win+R，输入cmd，回车，打开新的命令行，复制并运行以下命令。注意对应你安装的mongdb的版本：
mongodb v3 的导入命令为:
`mongorestore -h localhost -d leanote --dir C:\user1\leanote\mongodb_backup\leanote_install_data‘

但是我做到这一步的时候就报错：**SyntaxError: missing ; before statement**
我的系统是win7 32位

**Comment by lxh023** [comment]
mongorestore  -h localhost -d leanote  --directoryperdb C:\user1\leanote\mongodb_backup\leanote_install_data

**Comment by lealife** [comment]
请确保mongodb是否正常运行
