### ISSUE TITLE
Clean up old generated pdf

### ISSUE THREAD

**Issue by IndeedPlusPlus** [leanote/leanote#580]
While using `export to pdf`, pdf files do not get deleted after successful download. A lot of disk space will be wasted if these files accumulate.

One simple workaround is to create a cron job with following command
`find ~/leanote/files/export_pdf/ -name '*.pdf' -mmin +60 -delete`
to remove all pdf files older than 1 hour

**Comment by lealife** [comment]
Confirmed

**Comment by lealife** [comment]
Cron job is nice
