### ISSUE TITLE
个人博客自定义域名

### ISSUE THREAD

**Issue by wangxiaoyao** [leanote/leanote#581]
我已经在自己的服务器搭建了leanote。现在希望修改我自己博客的域名为主域名。 而不是leanote的注册页。 我应该怎么操作。 万分感谢。

**Comment by dreamingly** [comment]
修改conf/routes,第八行Get 	/			Index.Default为Get 	/			Blog.Index，默认应该是管理员的博客

**Comment by lealife** [comment]
后台管理有设置管理员博客的主页的选项
