### ISSUE TITLE
我不知道右边这个空白框有什么用

### ISSUE THREAD

**Issue by jiangshantao** [leanote/leanote#584]
![2017-04-10 3 13 50](https://cloud.githubusercontent.com/assets/25195806/24849923/823eb104-1e00-11e7-8445-4f22243c207b.png)

**Comment by lealife** [comment]
这是图片, 可能你的笔记有一个图片, 但这个图片很小, 看不出

**Comment by jiangshantao** [comment]
好的 原来是这样
