### ISSUE TITLE
部分网页复制粘贴到Leanote中内容会粘帖两遍，且粘贴反应很慢

### ISSUE THREAD

**Issue by TAXUEZJU** [leanote/leanote#588]
在用Leanote整理备份一些微信公众号里的文章时，发现一些文章复制粘贴后内容会出现两遍，在Windows上2.4版64位软件上和Linux上2.4版64位均出现此问题，在为知笔记上一切正常，排除我设备的问题，应该是Leanote的处理出了问题。
实测出现问题的网页：
1. [http://mp.weixin.qq.com/s?__biz=MzA4NTc1NTUzOA==&mid=2650120963&idx=1&sn=1d8b054ad745929a5d1de754bdd729f5&chksm=87d210feb0a599e823d118bbd6704c058f18bbe2feb66c802ec1db1ce7df25af7c04395732ec&scene=21#wechat_redirect](url)
2. [http://mp.weixin.qq.com/s/UXioMhEj4f3UPZfyQdOgwQ](url)
是否因为Leanote将网页中隐藏链接中的内容又再次显示了一遍。
另外实测Leanote粘贴网页内容奇慢无比，为知笔记反应迅速，大约一两秒，Leanote需要六秒以上，(测试设备性能较弱，在性能更好的设备上差距不算明显)望改进

**Comment by lealife** [comment]
confirmed
