### ISSUE TITLE
网页版退出的时候url出错

### ISSUE THREAD

**Issue by kevin-y-ma** [leanote/leanote#592]
这个项目真的非常好，自己搭建了一个也很好用，不过在网页版退出的时候url会自动指向http://localhost:9000/logout?id=1,而不是自己的远端ip，造成退出失败，这个bug应该很好修复，不过无奈自己不懂go。

再次向开发者表示感谢。

**Comment by lealife** [comment]
请修改conf/app.conf配置文件, site.url为外网访问的域名
