### ISSUE TITLE
希望增加用户笔记页面自定义CSS样式

### ISSUE THREAD

**Issue by raohuayu** [leanote/leanote#593]
希望增加用户笔记页面自定义CSS样式（自己看的笔记）
有的人喜欢红色，而有的人喜欢蓝色，有的人愿意折腾，有的人愿意安稳。
希望作者可以对外开放一个CSS设置。
以下为个人意见:
增加一个 text 字段，来自定义用户的css，更头像设置一样。

**Comment by lealife** [comment]
暂不支持
