### ISSUE TITLE
给Leanote提两个建议...

### ISSUE THREAD

**Issue by ireland2011** [leanote/leanote#596]
1. 左侧文件夹显示  可否按照Ulysses那样的设计, 增加一个icon, 这样显示的更加清晰
2. 对于外层文件夹, 它显示的数量能否是所有子文件的文件数量总和, 而不是外层文件夹文件的数量

Thanks

**Comment by lealife** [comment]
"对于外层文件夹, 它显示的数量能否是所有子文件的文件数量总和, 而不是外层文件夹文件的数量"
这个需求已很多人提出, 求提交pull request
请提交issue时, 标题用问题描述, 一个问题一个issue, 其它人好针对该问题讨论和开发
