### ISSUE TITLE
重新安装leanote客户端出错

### ISSUE THREAD

**Issue by TonyWang8904** [leanote/leanote#613]
删除了Leanote桌面客户端（windows10 x64），也删除C:\Users\用户名\AppData\Roaming\Leanote文件夹，然后重新解压安装了一个客户端，重新登录同步笔记，但是同步下来的笔记不包括图片和附件，请问是什么情况啊？

**Comment by idreamerhx** [comment]
#611 This issues may case  your same problem

**Comment by lealife** [comment]
请在web上看下该图片的地址

**Comment by TonyWang8904** [comment]
果然是site.url的问题，谢谢了。另外想咨询一下笔记在客户端删除是不是在数据库有单独的标记啊，因为现在同步下来后发现有一个笔记本下少了两篇笔记，依稀记得好像是客户端删除了，但是网页端没有删除。
