### ISSUE TITLE
如何设置开机启动

### ISSUE THREAD

**Issue by saower** [leanote/leanote#624]
system OS  : centos 6.8

thanks

**Comment by gaunthan** [comment]
Your question is not related to Leanote, actually you are asking how to run program on Linux startup .

About how to do that, please google "How to run program on Linux startup". This post may also help you: [What is the Linux equivalent of Windows Startup?](https://unix.stackexchange.com/questions/19634/what-is-the-linux-equivalent-of-windows-startup)

**Comment by saower** [comment]
@gaunthan  thanks

**Comment by luzpaz** [comment]
@gaunthan looks like you can close this

**Comment by gaunthan** [comment]
@luzpaz Oops...Looks like you @ the wrong person.
@saower Please close this issue if your question solved.
