### ISSUE TITLE
自建服务器（二进制）无法搜索博客，源代码安装的可以搜索博客

### ISSUE THREAD

**Issue by KennyDiff** [leanote/leanote#629]
自建服务器（二进制）无法搜索博客，源代码安装的可以搜索博客，，，这是何解呢？ 环境都一模一样，centos 7 minimal 最新的mongodb ，最新的 leanote （2.4），源代码是直接git下来master。。。 难道二进制的不是从源码编译出来的吗？

**Comment by KennyDiff** [comment]
仔细核对，发现二进制版本的theme文件夹，和github里的源代码的theme不一样，将正确的拷贝过来覆盖，问题解决。但是... 这么明显的缺陷，两个版本如此接近，不得不让人多虑这个缺陷产生的原因，因为耗费了我3天的时间在搭建环境测试上。
./leanote/public/blog/themes
./master/src/github.com/leanote/leanote/public/blog/themes
copy the source code version to the binary version ,fix this issue....

**Comment by wangkexiong** [comment]
They run the company and need to earn money from this. 
Actually this is the community version on Github, and they didn't tell from release notes.

**Comment by bobinshen** [comment]
本来想使用下看看的，看了楼主的评论，我还是歇了

**Comment by lealife** [comment]
@KennyDiff 自己不会部署, 怪谁?
"除了官方网站的收费版，其他部署出来的私服个个错漏百出，各种奇葩明显的缺陷" 你能列出来吗? 我们一个个对峙!!

**Comment by lealife** [comment]
@KennyDiff 二进制版不会实时打包, 会比源码晚

**Comment by lealife** [comment]
@KennyDiff 欢迎加LeanoteQQ群 155377541 @群主 对峙, 欢迎大家围观!!!!!!

**Comment by KennyDiff** [comment]
缺陷在v2ex里有更详细说明，如果 @lealife 想仔细了解一下的话，已经被leanote浪费了几周的时间，已经确信你们是刻意设置的门槛，不想继续再在你们的q群浪费时间。如果你们真心想改变，请按照我的环境部署了一眼就知我说的那些明显的缺陷了。
https://www.v2ex.com/t/370717

**Comment by KennyDiff** [comment]
我部署了以下 2.4 的最新版本 https://github.com/leanote/leanote/releases 
leanote-linux-amd64-v2.4.bin.tar.gz 
leanote-windows-amd64-v2.4.bin.tar.gz 
https://github.com/leanote/leanote.git (代码直接 git 下来部署) 

我不知道之前的版本是否这样，但这个版本的确缺陷让我很难受，我可以接受缺陷。但故意这么设置门槛导致的缺陷让人很无语。（因为 leanote.com 上所有的功能都是完整健壮的) 如果以上认为我委屈了 leanote 的可以自行下载此 2.4 版本的 release 看看我是否胡言乱语。 
缺陷如下：1. 无法修改 email( github 上回复得自己进数据库修改），可以接受，但 2 年了还不修复此缺陷，有点那个 
2. windows 二进制版本无法部署 wkhtmltox，怎么弄都无法成功，文档也没说，查看源码后参照格式也无法成功执行，放弃。 
3. 转 Linux，开始很顺利，部署好后，blog 打开是无法搜索的。一定是部署的方法不对，重新部署，blog 还是无法搜索 
4. 试试 Linux 上部署代码运行，Blog 可以搜索了（但是一安装本地 zip 的 theme，立即也无法搜索），但是编辑笔记经常假死，重启服务正常，长一点的 note 编辑后编辑界面就假死了。。。。 绝望弃坑。 

以上这些 bug （除了第一项无法测试） 其他的在 leanote。com 上均没有这些缺陷。 

我的环境贴一下： 
CentOS-7-x86_64-Minimal-1611.iso 
mongodb-linux-x86_64-rhel70-3.4.5.tgz 
Windows 2008 R2 
Chrome 59

**Comment by KennyDiff** [comment]
看到2.5版本已经修复我反馈的缺陷。
Export pdf on Windows
Blog search on latest version of Chrome
-----------------
我可以理解为
1. 这两个极其明显的缺陷的确是coder的失误（根据我知道的信息和经验，这个概率很小，因为github上之前已经讨论过这个缺陷并未被关注）
2. 这两个缺陷是leanote.com公司的某种不得以的决策行为(理解你们的生存压力)
不论leanote.com公司的决策如何影响了github的代码，我还是很感谢coder们的贡献。

**Comment by yw80** [comment]
@lealife 我作为旁观者，可能楼主说的“假开源”的情况存在，但我不认可。我觉得，更像是你们不会用 github。比如，我会看到 2015年3月份 的 Pull requests 还没处理，Issues 更是积攒了从 2014 年开始多达 309 个反馈没有处理完，已经解决了的问题却不及时 close。所以，虽然我并不赞同“假开源”的观点，但我觉得你们并没有以 github 做为开发中心，或者说，你们存在闭源与开源两套代码，这个事实，似乎是有的。调整开发模式，也很重要。否则，如果别人看到 2015年 的 Pull requests，怎么会有兴趣继续提交代码呢。。

**Comment by lealife** [comment]
@KennyDiff 
"这两个极其明显的缺陷的确是coder的失误（根据我知道的信息和经验，这个概率很小，因为github上之前已经讨论过这个缺陷并未被关注）
这两个缺陷是leanote.com公司的某种不得以的决策行为(理解你们的生存压力)
不论leanote.com公司的决策如何影响了github的代码，我还是很感谢coder们的贡献。"

听到你的言论, 我很生气, 欢迎大家围观!!

1. 博客搜索之前已经提交到github上, 只是没有发布release打包成二进制!!
2. PDF导出, 为什么官网上可以, 为什么你用linux安装可以? 你觉得leanote.com的服务器是用windows的? 我们开发Leanote之前就根本没想到为Windows兼容, 为了支持windows, 为了支持多语言, Leanote开源做额外做了大量的工作, 而这些代码我们leanote.com其实根本不需要!!!!!!!!!! 你还在这里说"不得已的决策行为", 让我很气愤!!

**Comment by KennyDiff** [comment]
@lealife 好吧，消消气，我知道你是这个项目的主要贡献者，也猜测你是leanote.com的合伙创始人之一，就当我上面那些猜测是胡说八道吧，但我的部署测试经过都是事实，供你参考。 另，根据你上面说的，你们没有足够资源（我这样理解不知道对不对）来维护github.com上对windows、多语言的支持。希望大家来贡献leanote项目代码。不知道怎么说好，别人的pull reqeusts被你们无视，自己又不管，放着几年不可用，也不告知大家这个东西不可用，包装成一个很完美的像mysql，apache，centos这样的开源产品吸引大家信任，然后浪费一部分人的时间去部署（我算一个吧）。 我一直这么认为：一个人可以随意浪费自己的时间，那不叫浪费，是他选择自己的生命去如何度过，但如果是随意甚至故意去浪费其他人的时间就是有罪的。 
 建议你们如果没有足够资源维护windows版本或者多语言版本， 请关闭掉这个平台的支持。或者在Introduction上注明windows版本的成熟度很低，告知大家一下。

**Comment by lealife** [comment]
@KennyDiff 抱歉, 浪费你时间了. 请无视Leanote

**Comment by yw80** [comment]
@lealife 我没读过 leanote 源码。不过，作为开发者，做多平台项目通常都是要有一个兼容层的，在兼容层之上再做一致的开发。从这点上来说，leanote 不应该出现只在 windows 平台下特有的 bug（或者是因为你们缺乏足够的架构能力）。尤其当你说出 “我们开发Leanote之前就根本没想到为Windows兼容” 显得你很狭隘。
对于 @KennyDiff 的反馈，事实存在，但是原因不一定是他说的那样。导致大家乱猜的原因，是因为一个既定事实。你要做的很简单啊，解决问题即可，而不是解释。在事实面前，任何解释都是苍白的。
看 github 上最近几次提交的日期：8-9、8-2、7-27、6-21、6-20、5-19、4-16，这与当前 306 个 Issues 是鲜明的对比。
尽快完善项目吧，加油~

**Comment by KennyDiff** [comment]
你误会我了，我不是说希望Leanote关闭Github的项目，是关闭对windows的支持，专心做好Linux的版本，稳定可靠，让人信任，就像CentOS一样。

**Comment by lealife** [comment]
@yw80 我们现在讨论的是Leanote server端, 作为server, 以当前的服务器使用情况来说, 不应该首先支持Linux?  如果一个server支持Windows, 那是它的加分项而不是必须项.

* "尤其当你说出 “我们开发Leanote之前就根本没想到为Windows兼容” 显得你很狭隘。". 我们当初开发这个产品的时候如果想着我们的Leanote要运行Windows服务器上, 是不是很可笑!
* "leanote 不应该出现只在 windows 平台下特有的 bug" 任何软件. 对于Windows, 现在已知的BUG已解决, 就只是一个PDF导出的问题. 

用一个PDF导出的BUG来在这里说Leanote这那的, 我当然受不了!! 当然, 我们接受批评.

以后, Leanote仍以支持Linux, mac为首要任务.

欢迎提交pull request, 这是比这里讨论更实在的支持!! 那些之前没有关闭的pull request实在是没有解决问题, 而我只是想留在那里, 作为参考. 并不是我没有处理.

**Comment by yw80** [comment]
@lealife 你说”想着我们的Leanote要运行Windows服务器上, 是不是很可笑!“，恕我直言，我觉得你这么说，只能体现出你们团队非常狭隘且可笑。。。
我也是 IT 领域的，我非常清楚的知道一些狭隘的技术员只认 Linux 和 Mac。殊不知，根据 IDC 的统计，Windows Server 的份额在 2009 年就超过了 Linux。在中小企业市场，由于缺少专业的维护人员，Windows Server 的市场份额很高，不容忽视。比如一个锅炉制造的企业，你无法要求他们配备 Linux 管理员，但他们的确有自建笔记系统的需求。
至于 Android 的份额超过 IOS 更是人尽皆知的事实。1Q17，Android 的市场份额超过 86%。做为 IT 从业人员，不应该看不到 Mac 暗淡的前途。
技术服务于需求，无视需求的技术，是盲目的。将产品定位于小众市场，是对团队极大的不负责。

PS: 无意参加争论，纯粹是不希望国产团队失败在认知上。

**Comment by xingstarx** [comment]
@lealife 不想多说什么，只觉得leanote的团队得继续努力，让leanote更加完美，让美好的事物持续发生，而不是把精力浪费在这种无意义的争吵上。

**Comment by lealife** [comment]
@xingstarx 多谢建议, 无意争吵, 只是因某些人就一点Bug而对软件和开发人员进行指责和恶心揣度实在不能忍.
此issue就此关闭, 不再提.
