### ISSUE TITLE
Windows版本的二进制安装无法使用转PDF的功能（Linux的可以)

### ISSUE THREAD

**Issue by KennyDiff** [leanote/leanote#630]
Windows版本的二进制安装无法使用转PDF的功能。 Linux的安装的就可以是用PDF。 但无法搜索博客， source版的安装就基本上功能OK。。。 缺陷如此明显，可能人力资源有限，也可能是其他原因。

**Comment by lzhr** [comment]
\src\github.com\leanote\leanote\app\controllers\NoteController.go

	cmd := exec.Command("/bin/sh", "-c", cc)
	_, err := cmd.Output()
	if err != nil {
		return c.RenderText("export pdf error. " + fmt.Sprintf("%v", err))
	}

**Comment by lealife** [comment]
2.5 fixed
