### ISSUE TITLE
安装好，无法登陆。已排除leanote 安装/配置问题汇总

### ISSUE THREAD

**Issue by jileilei** [leanote/leanote#637]
开启服务后，返回一个进程号，如下：
nohup /bin/bash /home/leanote/bin/run.sh >> /var/log/leanote.log 2>&1 &
[2] 16487

没有出现证明成功的信息啊
最后出现以下信息证明运行成功:

...
TRACE 2013/06/06 15:01:27 watcher.go:72: Watching: /home/life/leanote/bin/src/github.com/leanote/leanote/conf/routes
Go to /@tests to run the tests.
Listening on :9000...

**Comment by lealife** [comment]
请检查是否是数据庫连接问题
