### ISSUE TITLE
Unable to read locale cookie with name 'LEANOTE_LANG'

### ISSUE THREAD

**Issue by ruihuowayking** [leanote/leanote#652]
一次服务器掉电之后,leanote无法启动,查看日志提示
TRACE 2017/08/19 18:10:35 i18n.go:218: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present
TRACE 2017/08/19 18:10:35 i18n.go:184: Found Accept-Language header value: zh-CN

请问怎么解决?

**Comment by lealife** [comment]
不是问题, 请忽略

**Comment by renguzi** [comment]
二进制安装leanote最新版本：64: leanote-linux-amd64.v2.5.bin.tar.gz 

配置了NGINX代理之后，浏览器访问时，命令行上有看到下述错误：

TRACE 2017/11/28 16:38:04 i18n.go:218: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present
TRACE 2017/11/28 16:38:04 i18n.go:184: Found Accept-Language header value: en-US
2017/11/28 16:38:03.980 127.0.0.1 500 125.385267ms GET /
2017/11/28 16:38:04.163 127.0.0.1 404  816.464µs GET /style.css

**Comment by renguzi** [comment]
@renguzi
自己遇到的问题现象，已经解决，在另外一个帖子。
https://github.com/leanote/leanote/issues/330
