### ISSUE TITLE
脚本执行漏洞，博客描述处，可以嵌入<script>

### ISSUE THREAD

**Issue by Nigh** [leanote/leanote#66]
不知道是 feature 还是 bug ...

不过可以使用open来弹窗...

其他地方应该也有..

重现地址： http://nina.leanote.com/

**Comment by leanote** [comment]
你好, 可以不算是bug, 描述都可以用html, 这样更容易控制, 博客是自己的, 可以随意折腾.                             Original Message                             Sender: Nigh<notifications@github.com>Recipient: leanote/leanote<leanote@noreply.github.com>Date: 星期六, 1月 24, 2015 13:51Subject: [leanote] 博客描述处，可以嵌入<script> (#66)不知道是 feature 还是 bug ...

不过可以使用open来弹窗...

重现地址： http://nina.leanote.com/
