### ISSUE TITLE
leanote跨服务器前移问题

### ISSUE THREAD

**Issue by ddzzhen** [leanote/leanote#663]
当跨域名服务器迁移时,mongo数据库的迁移正常,但由于图片和链接的保存方式与site.url有关,更换服务器之后域名一旦发生变化,笔记中的链接(主要是图片)就会丢失,因此:
(1)笔记数据库无法跨域名迁移!
(2)此外,在迁移过程中丢失一个笔记的文字,数据全部丢失,暂未发现原因,其它的笔记都正常恢复,除了没有链接(图片等).
使用的版本是最新的64位,系统Ubuntu14_64位.

**Comment by ddzzhen** [comment]
the leanote folder has "files" which is including links especially images, so it can display the links now.

**Comment by jonchin** [comment]
有方法解决吗？换域名后site.url 也变更了，图片还是显示旧的
