### ISSUE TITLE
Illegal / Invalid host

### ISSUE THREAD

**Issue by helisaire** [leanote/leanote#665]
Hello,

I'm from France. It's hard for me to understand chinese... Leanote seems to be the only app which meets all my criterias.

I've installed the server binaries on my linux vps. Everything is ok. With my browser, I can acess to MY_VPS_IP.ovh.net:9000. But with the windows and android clients, I have the message : invalid / illegal host.

I've edited /leanote/conf/app.conf to add MY_VPS_IP.ovh.net:9000 to siteurl. But it doesn't work.

Thanks for you amazing works !

**Comment by puresox** [comment]
maybe you should add 'http://' or 'https://' like this 
![snipaste_20170918_201623](https://user-images.githubusercontent.com/17718921/30541535-6e243ea0-9cae-11e7-903b-f75a6c894902.png)

**Comment by lealife** [comment]
@puresox Service url should be prefixed with https:// or http://
