### ISSUE TITLE
导出PDF后，代码高亮失效，变为黑白

### ISSUE THREAD

**Issue by EricCong2016** [leanote/leanote#666]
原来的markdown预览
![image](https://user-images.githubusercontent.com/24240849/30574672-1cc3e8dc-9d2e-11e7-8e69-e25cf0fa101b.png)
导出pdf后
![image](https://user-images.githubusercontent.com/24240849/30574692-53963428-9d2e-11e7-92eb-d8a271cea84f.png)

**Comment by EricCong2016** [comment]
而且行数也不显示

**Comment by ikelaiah** [comment]
How did you do that? Whenever I save as PDF from Chrome or Firefox, I ended up with an empty PDF file.

I tried to use [dilinger.io](https://dillinger.io/). The output missing line numbers and formatting.

**Comment by ikelaiah** [comment]
I managed to print to PDF by using Win desktop client. The problem is, the PDF export is inconsistent. Just like EricCong2016's output.

Could someone help?

**Comment by lealife** [comment]
导出PDF非常耗时, 所以一些耗时的渲染就去掉了

**Comment by whuwangyong** [comment]
可以弄成可配置项吗？PDF演示的时候高亮代码比较明晰
