### ISSUE TITLE
leanote安卓客户端不显示图片

### ISSUE THREAD

**Issue by shf4715** [leanote/leanote#669]
如题，服务端为2.4版本，安卓客户端列表预览中图片显示为obj的小方框，点开笔记后不显示图片，这个是bug吗，还是其他什么原因所引起的。

**Comment by pleasecallmemaoxian** [comment]
官方的教程说的是，请确保app.config里面的siteurl与客户端地址一致，一般问题的确也就出在这

**Comment by shf4715** [comment]
有什么办法能解决这个问题吗，我pc端存在域名映射问题，但已经存了很多内容在私有服务器上。

**Comment by pleasecallmemaoxian** [comment]
这个的话你可以试下导入导出，不过提前先做好备份吧，我也没尝试过这种

**Comment by shf4715** [comment]
已确认问题，我用docker部署的服务，虽然我绑定了域名端口，但是映射的时候我将原9000端口映射到了19000端口，因为域名端口不一致导致的笔记不能正确同步，现已修复。
