### ISSUE TITLE
docker 启动是空白页面

### ISSUE THREAD

**Issue by yusank** [leanote/leanote#670]
通过 wiki 里边的教程启动了 docker 容器，但是方式端口是得到一片空白，但是网页的 icon 是加载出来了，其他什么都没有，any idea?

**Comment by jetgeng** [comment]
应该是数据没有初始化。你在代码中找到数据，然后倒入到 mogodb 中。应该能工作。我现在就是用 docker 跑的。

**Comment by yusank** [comment]
嗯嗯，后来倒腾出来了，是数据库的问题，谢谢

**Comment by andyhuai** [comment]
你是专门弄好的，我在docker里面，9000端口访问不了，根本没有连接上
