### ISSUE TITLE
Never loads notes.db

### ISSUE THREAD

**Issue by firewater2** [leanote/leanote#679]
All your notes are in notes.db. Upon startup Leanote never stops loading, and never gets to the login screen. I can load the notes.db file on a text editor and thankfully the content is there, on a huge file of 300mb, but Leanote won't open it. These are all my notes. This is my life. Please help.

edit: by a miracle, I managed to fix this. What I did was: I had a backup of a previous notes.db from a month ago (which only weights 25mb and is recognized by Leanote), and then my most current corrupted notes.db. I opened both of them on a text editor, and there I saw the .db files are stored in plaintext, so I spent a good chunk of time manually copying stuff from the most recent one to the old, working file.

I'm not closing this because it is still a bug. I did nothing wrong. Somehow my notes.db file just had 2500~ paragraphs of the same note copied again and again, basically all variations of it were stored.

**Comment by lealife** [comment]
Please try to use Leanote Desktop 2.6 https://sourceforge.net/projects/leanote-desktop-app/files/

**Comment by firewater2** [comment]
Thanks! I hope this doesn't happen again with this version. Everything has been fine since I fixed the issue. I like the new search dialogue that doesn't reset to the beginning of the page if you have writing enabled, too!
