### ISSUE TITLE
Error when running Leanote 2.5 within Docker

### ISSUE THREAD

**Issue by romu70** [leanote/leanote#683]
I'm trying to setup a Docker container to run Leanote 2.5, and it's pretty hard!

After some days of digging around, I've an almost working container, but it's not really great. Currently, when I connect my container (http://address:port), I get an empty page, the code is:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="leanote,leanote.com">
<meta name="description" content="leanote, not only a notebook">
<meta name="author" content="leanote">

<title>

    
</title>

<link href="" rel="stylesheet">

<link href="" rel="stylesheet">
<link href="/style.css" rel="stylesheet">
<script>
function log(o) {
}
</script>
<style>

</style>
</head>
<body>

<div id="headerAndNav" >
	<div id="headerContainer" class="container">
		
		<div id="header">
		
			
			<h1>
				<a href="" id="logo">
```

As you can see, the page is not complete!

I get some strange traces in the log:

```
[0m[0;35mTRACE 2017/11/06 21:25:07 i18n.go:218: Unable to read locale cookie with name 'LEANOTE_LANG': http: named cookie not present
[0m[0;35mTRACE 2017/11/06 21:25:12 i18n.go:187: Unable to find locale in cookie or header, using empty string
```

Any idea?

**Comment by romu70** [comment]
hello??

**Comment by joseba** [comment]
Did you follow this step?
https://github.com/leanote/leanote/wiki/leanote-binary-installation-on-Mac-and-Linux-(En)#3-import-initial-leanote-data

**Comment by romu70** [comment]
Yes. In the meantime, I found the cause of the issue, even if I haven't found any fix yet. The problem happens when I run my Mongo container with authentication. If I run Mongo without authentication, no problem. I investigate.
