### ISSUE TITLE
How about enlarging the editing area?

### ISSUE THREAD

**Issue by Magicloud** [leanote/leanote#69]
Currently, when editing a markdown note. The view box is generally split into four columns. Notebooks, articles, raw text, markdown rendering. With low resolution, widths the four columns are almost equal, which means the actual editing area is pretty narrow.

How about allowing the user to minimize or hide the notebooks, articles zone?

**Comment by leanote** [comment]
![image](https://cloud.githubusercontent.com/assets/6499273/5895476/f8a4d654-a55b-11e4-80b5-4e7c1b1e41dd.png)
Please click the highlight area to hide the left column.

**Comment by Magicloud** [comment]
Ah, thank you.
