### ISSUE TITLE
XSS to code execution

### ISSUE THREAD

**Issue by silviavali** [leanote/leanote#695]
This issue should not be closed before being fixed. Also I have made a request on full disclosure on the issue.

https://github.com/leanote/leanote/issues/694

**Comment by thefLink** [comment]
Devs of a 6k star project should be ashamed

**Comment by lealife** [comment]
@silviavali Your report is the Leanote Desktop' issue. Please reopen an issue at Leanote Desktop https://github.com/leanote/desktop-app

**Comment by silviavali** [comment]
Thanks for the info!
