### ISSUE TITLE
只能用localhost访问，不能用ip或域名访问

### ISSUE THREAD

**Issue by nonesuccess243** [leanote/leanote#709]
服务器环境为centos 7

修改app.conf中的site.url，将localhost改为ip或者域名，再启动run.sh的时候，debug信息都显示Listening on., localhost:9000。

在本地wget localhost:9000 正常，wget ip:9090，显示connection refused。

在外网访问ip:9000，拒绝连接

防火墙已经打开了9000端口，将防火墙整体关闭后，效果不变。

在app.conf文件中将端口号随便改成其它端口，再启动，debug信息显示Listening on., localhost:9009，证明没有找错文件。

请问这是怎么回事

**Comment by hanwangkun** [comment]
只能通过增加nginx作为反向代理来进行远程访问

**Comment by vector090** [comment]
设置 http.addr=所需IP 即可

**Comment by JerryJiangjjw** [comment]
server {
        listen       9001 ;
        location / {
            proxy_pass http://127.0.0.1:9000;
        }
    }
我是通过配置nginx解决

**Comment by oldFuryBird** [comment]
**注意 ： leanote  的http.addr 藏在下面 离http.port很远，**
修改 http.addr=0.0.0.0
