### ISSUE TITLE
管理员不能将用户名改为非 admin ，否则将看不见“后台管理”的菜单

### ISSUE THREAD

**Issue by linux-mac** [leanote/leanote#71]
管理员不能将用户名改为非 admin ，否则将看不见“后台管理”的菜单，这是BUG吗？

**Comment by xuxueyun** [comment]
leanote-linux-x86_64.v1.0-beta.3 版本

**Comment by leanote** [comment]
请将conf/app.conf文字增加一个配置:adminUsername=修改后的用户名                             Original Message                             Sender: Daniel<notifications@github.com>Recipient: leanote/leanote<leanote@noreply.github.com>Date: 星期一, 1月 26, 2015 11:53Subject: [leanote] 管理员不能将用户名改为非 admin ，否则将看不见“后台管理”的菜单 (#71)管理员不能将用户名改为非 admin ，否则将看不见“后台管理”的菜单，这是BUG吗？

**Comment by leanote** [comment]
请将conf/app.conf文字增加一个配置:
adminUsername=修改后的用户名

**Comment by DevonLiu0** [comment]
我也遇到这个问题了 =,= 。。。
在 app.conf 中添加用户名无效， 是否还需要在其他地方配置 ？

**Comment by lealife** [comment]
adminUsername=修改后的用户名 就能解决. 请重启leanote

**Comment by DevonLiu0** [comment]
解决了。
对 revel 不是很熟悉。  重新 `revel build` 过了， 查看 `build` 后的目录里面 `app.conf` 也修改了， 然后 `run.sh` 还是无效。 不知是哪里问题。
最后无奈之下重启了服务器， 问题解决。
