### ISSUE TITLE
bind to a site.url don't work

### ISSUE THREAD

**Issue by d4kr** [leanote/leanote#717]
Hi, 

I have binded my leanote website to a site.url in app.conf like the example

`site.url=http://note.mysite.com:9000`

but when I start leanote with bash run.sh I alway get the listening on localhost...

```
DEBUG 20:36:40  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go
Listening on.. localhost:9000
```

If i try to connect from a remote host don't work, if I try to connect from localhost (with telnet) it works. I have tried to change the port to 80 (stopped my apache service before) but without chance.

There is something wrong I do?

Thanks

Server configuration:

- Ubuntu 16.04
- Go 1.6.2
- Int IP Address:	10.1.2.3
- Pub IP Address:	x.x.x.x

**Comment by JerryJiangjjw** [comment]
same to me, and i add edit nginx.conf to solve it 
```
server {
        listen       9001 ;
        location / {
            proxy_pass http://127.0.0.1:9000;
        }
    }
```

**Comment by lealife** [comment]
If you wanna listen all ip, please find and update `app.conf`

```
http.addr=0.0.0.0 # listen on all ip addresses
```
