### ISSUE TITLE
功能建议：批量导出.md 文件

### ISSUE THREAD

**Issue by skyhiter** [leanote/leanote#736]
对于强迫症来说，保存md文件最稳妥～

**Comment by gaunthan** [comment]
API是开放的，可以自己写一个dump工具。

其实，这样的轮子已经有了：[gaunthan/Leanote4MD](https://github.com/gaunthan/Leanote4MD)。

**Comment by gaunthan** [comment]
最近无聊又重新造了个轮子，[gaunthan/leanote2md](https://github.com/gaunthan/leanote2md.git)。

可以导出hexo文章元信息，文章图片输出路径和引用格式等。代码结构和文档说明比这个要清晰些。

欢迎大佬们提建议:-D

**Comment by skyhiter** [comment]
谢谢回复，我去看看。

**Comment by yunying61** [comment]
> 最近无聊又重新造了个轮子，[gaunthan/leanote2md](https://github.com/gaunthan/leanote2md.git)。
> 
> 可以导出hexo文章元信息，文章图片输出路径和引用格式等。代码结构和文档说明比这个要清晰些。
> 
> 欢迎大佬们提建议:-D

感谢
