### ISSUE TITLE
Sorry. not an issue but..

### ISSUE THREAD

**Issue by CodingCreate101** [leanote/leanote#738]
Sorry. not an issue but just wondering, it says it's an open source tool but on their site, they have pricing plans here: https://leanote.com/pricing#personal_service

So, what exactly is going on here?

**Comment by sabueso** [comment]
Hosted version? Anyways, this is not an issue... and you know...

**Comment by CodingCreate101** [comment]
I know but there is no way to contact them from that site. So, I was wondering if I could get more info here, at least. Could you please explain what's the difference between stuff on their site and ones that are available here?

**Comment by mariusv** [comment]
@CodingCreate101 , there is no difference. OpenSource doesn't means free ;-) .
you have two options:
1. Host it yourself for free (hosting costs will occur)
2. pay them to use their hosted one

**Comment by oktayaa** [comment]
Their regular hosted solution is free to use. I think you pay for premium features which  include more traffic, more concurrent sync options etc. Please do not spread FUD. Do your research first.

**Comment by CodingCreate101** [comment]
Understood. The code itself is free to use however they are offering hosting plans. Thanks, guys. :)
