### ISSUE TITLE
源码安装后执行 bash run.sh 提示错误

### ISSUE THREAD

**Issue by iwantacook** [leanote/leanote#741]
非常感谢官方文档的提示，目前已经成功完成了mongodb数据库的安装和导入。
并将源码文件下载到了自己的目录（ubuntu系统）
/home/leanote/
在目录：/home/leanote/bin/下执行bash run.sh命令的时候，提示无文件；
执行bash run开头的文件，同样会有错误提示，贴代码：
chmod: cannot access '/home/leanote/bin/leanote-linux-amd64': No such file or directory                                                                                                                                  
run-linux-amd64.sh: line 18: /home/leanote/bin/leanote-linux-amd64: No such file or directory 
说明文档提示的路径是/home/user1/leanote/bin，这个影响大吗？

**Comment by lealife** [comment]
你好, 官方文档并没有 `bash run.sh`, 请不要这样启动Leanote. 请使用文档提供的方法启动

**Comment by iwantacook** [comment]
@lealife 不好意思，我是暂时没有找到启动文档提供的启动方法，我再仔细找找，谢谢！

**Comment by iwantacook** [comment]
最后采用源码安装，可以正常启动并登陆使用，非常感谢！
