### ISSUE TITLE
Large Image Fail to Sync in Note 大图像无法同步

### ISSUE THREAD

**Issue by motowizlee** [leanote/leanote#748]
Just started to use Leanote and loving it so far. However faced some issue that I am not sure if it is a bug or configuration problem.

Below are the setup of my system:

Local Leanote Server: v2.6.1
Mongo DB: v3.6.3
Leanote Desktop: v2.6

Step to reproduce, [this is the image that causes the sync error (~24MB)](http://orig00.deviantart.net/1ddc/f/2009/203/1/c/computer_hardware_poster_1_7_by_sonic840.png). 

- If the web client to add the image, the desktop client is able to sync but fail to display the image
- If the desktop client is use to add the image, it will have an error icon saying "Message : Undefined" Error
- All the other notes with images and attachment sync successfully

**Edit**: Found that it is not only large picture. It is the picture that is copy pasted from clipboard that will fail to sync. The image that is inserted from the "Insert/edit image" button will sync just fine.

Would love to provide more details and even in mandarin if needs to. I am a native Chinese speaker although I am able to communicate better in English for technical terms.

Thanks in advance!

**Comment by wxlg1117** [comment]
web后台更改最大值大小
![qq 20180403095247](https://user-images.githubusercontent.com/9752596/38224921-dcacacd4-3724-11e8-819f-6a3347987c59.jpg)

**Comment by motowizlee** [comment]
Thanks @wxlg1117 ! After modifying the setting there's no issue anymore. Will proceed to close this issue.
