### ISSUE TITLE
使用腾讯云搭建二进制版，bash run.sh 提示Listening on :9000...后无法登陆

### ISSUE THREAD

**Issue by xinchangliang** [leanote/leanote#750]
bash run.sh 后提示Listening on :9000... 终端界面也没有被占用，进程中也找不到。

**Comment by wxlg1117** [comment]
提示已经正常监听,那说明程序跑起来了

**Comment by xinchangliang** [comment]
问题找到了，腾讯云 网卡填的是内网IP， 在app.conf 中的http.addr项不能填公网IP,要填内网IP。
