### ISSUE TITLE
图标驻留在任务栏中

### ISSUE THREAD

**Issue by yangdaweihit** [leanote/leanote#752]
将程序图标在驻留任务栏中（甚至加上快捷键弹出和缩回），是提升leanote使用频次的重要方式，直接影响到用户的体验。建议尽早丰富这个功能。
另，leanote的图标是否应重新设计一个。蚂蚁的图案可以设计得很漂亮的。

祝越做越好！

**Comment by lealife** [comment]
早就有这个功能了
