### ISSUE TITLE
源码安装运行时报错 must be imported as github.com/revel/modules/static/app/controllers

### ISSUE THREAD

**Issue by haotian2546** [leanote/leanote#760]
revel  build.go:146: ..\src\github.com\leanote\leanote\app\tmp\main.go:19:2: must be imported as github.com/revel/modules/static/app/controllers

**Comment by rvier** [comment]
把   盘符:\Go\src\github.com\leanote\leanote\vendor 文件夹删了

**Comment by rvier** [comment]
[（都8012年了还有这种问题）](https://github.com/leanote/leanote/issues/714)    Issue重复，建议关闭 @lealife
