### ISSUE TITLE
可以强制把客户端数据同步到服务端不？

### ISSUE THREAD

**Issue by printff** [leanote/leanote#761]
自建。
因为服务端数据丢失，只能用备份恢复。
客户端的数据比服务端要新，但同步时提示“服务端笔记不存在”。
请问可以强制把客户端数据同步到服务端不？谢谢

**Comment by Leiouflying** [comment]
目测不行，如果不多尝试用复制重建
建议重要的服务建立daily的计划任务做备份

**Comment by Leiouflying** [comment]
可以通过导入导出功能“强制”同步的
1.客户端导出笔记（记得选整个笔记本哦，要不然一份一份点很累的）
2.导入，然后就能恢复数据了

**Comment by printff** [comment]
是一种解决方法，谢谢啦
像xmarks生前是可以强制同步到服务端的，但估计这需求量比较小
