### ISSUE TITLE
自制证书弄的ssl，安卓端不能进入

### ISSUE THREAD

**Issue by iwantacook** [leanote/leanote#763]
我用自制证书弄的ssl，桌面客户端能进入，手机安卓客户端进不了，提示“网络错误”
是证书的问题么？
安卓版本：1.0.0 bate7

**Comment by sheerfish999** [comment]
你这问题我也遇到了， 自签发或外部证书都不行， 但是其它APP就可以
要么是APP问题， 要么是特定证书才行

**Comment by ever2010** [comment]
试过了，自签名证书的话，在安卓里先安装证书才行
（将crt文件拷到sd卡里，点设置--安全--从存储设备安装）
，我是安装了我自己的CA证书，成功了，直接安装用户证书应该也行。

**Comment by xingstarx** [comment]
嗨 android端目前已经解决了这个问题，可以使用体验啦，https://github.com/leanote/leanote-android/releases/tag/v1.0-beta.8.4

**Comment by lijingjian001** [comment]
这个issue是不是可以关了啊,看着这么多问题.我都没勇气升级账户了。

**Comment by xingstarx** [comment]
关了吧，不想升级账户，可以自建服务器啊

**Comment by iwantacook** [comment]
最后提一句：再反馈问题后，有相关的工作人员，已经联系我并处理完问题了。而且即使不处理这个问题，也不是不能使用。至于对产品或者是否升级的选择，看自己对问题的理解。很感谢有这样一款产品。
