### ISSUE TITLE
如何绑定阿里云

### ISSUE THREAD

**Issue by swimmingchar** [leanote/leanote#768]
请问怎么绑定阿里云的域名？

**Comment by cnlzxin** [comment]
我是域名解析到服务器, 然后配的 `Nginx`

**Comment by cnlzxin** [comment]
没看明白你的意思, 如果你的 `leanote` 是部署在服务器上, 那么在同一服务器上再配下 `Nginx` 就可以, 并不是在第二台服务器上配置
