### ISSUE TITLE
How to install a SSL certificate / translation

### ISSUE THREAD

**Issue by macbroadcast** [leanote/leanote#77]
hello @lealife 

i would like to install a ssl certificate , but i cant find any how-to mentioning it and i would like to translate it to german. :+1:  keep up the great work

Thanks

**Comment by lealife** [comment]
Hi, I am so happy that your your attention about Leanote. It's recommend that you can install a ssl by Nginx. The https://leanote.com use the Nginx to provide reliable service.

**Comment by lealife** [comment]
"i would like to translate it to german." Thanks you very much. Now the Leanote's language just support Chinese and English(Maybe not very well). If you have any problem, please feel free to let me know. Thanks again.

**Comment by linux-mac** [comment]
我用 nginx 的，但是 https://note.linux-mac.com/blog 页面有一个css不知是怎么出来的
https://note.linux-mac.com:9009/css/font-awesome-4.2.0/css/font-awesome.css

**Comment by lealife** [comment]
http://note.linux-mac.com:9009/css/font-awesome-4.2.0/css/font-awesome.css 是好的, 但是https://note.linux-mac.com:9009/css/font-awesome-4.2.0/css/font-awesome.css 不能显示, 可能是你的nginx配置有问题. 请检查下
https://leanote.com/note 官网下也用了font-awesome

**Comment by linux-mac** [comment]
# Solutions: #

## Use Nginx As Reverse Proxy Server(https) for leannote: ##

**1. Setup http://linux-mac.com jump to https://linux-mac.com, Key parameters: `/etc/nginx/conf.d/default.conf `**
    
```
server {
    listen       80;
    server_name  note.linux-mac.com;
    rewrite ^(.*)$  https://$server_name$1 permanent;
    access_log  /var/log/nginx/log/host.note.http.access.log main;
}
```
**2. Setup NginX Proxy for leanote, Key parameters: `/etc/nginx/conf.d/note.conf` **
```
server {
    listen 443;
    server_name leanote.linux-mac.com;

    ssl                  on;
    ssl_certificate      /etc/pki/tls/certs/linux-mac.crt;
    ssl_certificate_key  /etc/pki/tls/certs/linux-mac.key;

    access_log  /var/log/nginx/log/host.note.https.access.log main;

    location / {
        proxy_pass              http://127.0.0.1:8009;
        proxy_set_header        Host                    $http_host;
        proxy_set_header        X-Real-IP               $remote_addr;

    }
}
```
**3. Modification : `github.com/leanote/leanote/conf/app.conf`**
```
#------------------------
# leanote config
#------------------------

http.port=80

site.url=https://note.linux-mac.com
```

**4. run leanote :**

revel run github.com/leanote/leanote dev 8009

**Comment by linux-mac** [comment]
# Solutions: #

## Use Nginx As Reverse Proxy Server(https) for leannote: ##

**1. Setup http://linux-mac.com jump to https://linux-mac.com, Key parameters: `/etc/nginx/conf.d/default.conf `**
    
```
server {
    listen       80;
    server_name  note.linux-mac.com;
    rewrite ^(.*)$  https://$server_name$1 permanent;
    access_log  /var/log/nginx/log/host.note.http.access.log main;
}
```
**2. Setup NginX Proxy for leanote, Key parameters: `/etc/nginx/conf.d/note.conf` **
```
server {
    listen 443;
    server_name leanote.linux-mac.com;

    ssl                  on;
    ssl_certificate      /etc/pki/tls/certs/linux-mac.crt;
    ssl_certificate_key  /etc/pki/tls/certs/linux-mac.key;

    access_log  /var/log/nginx/log/host.note.https.access.log main;

    location / {
        proxy_pass              http://127.0.0.1:8009;
        proxy_set_header        Host                    $http_host;
        proxy_set_header        X-Real-IP               $remote_addr;

    }
}
```
**3. Modification : `github.com/leanote/leanote/conf/app.conf`**
```
#------------------------
# leanote config
#------------------------

http.port=80

site.url=https://note.linux-mac.com
```

**4. run leanote :**

revel run github.com/leanote/leanote dev 8009

**Comment by leanote** [comment]
Thanks @linux-mac, closed.

**Comment by macbroadcast** [comment]
thanks a lot  @linux-mac  :+1:

**Comment by mhoffmann75** [comment]
For all having sync problems with nginx, remember to add the following statement to your `nginx.conf`:
`client_max_body_size 20M;`
Adjust `20M` to whatever you specify as maximum image/attachment size (in Megabyte) in leanote. Otherwise nginx will stop larger notes from syncing.
