### ISSUE TITLE
Archlinux Leanote发生crash无法启动

### ISSUE THREAD

**Issue by skyox** [leanote/leanote#792]
**Arch 升级后leanote无法启动，core dumped**
```
Archhost@niuzhy:~>>> Leanote 
Failed to get crash dump id.
Report Id: 
Segmentation fault (core dumped)
```
**检查日志如下：**
```
Archhost@niuzhy:~>>> journalctl -r 
-- Logs begin at Fri 2018-05-11 03:28:46 CST, end at Fri 2018-06-15 08:31:06 CST. --
Jun 15 08:31:06 Archhost systemd-coredump[23620]: Process 23610 (Leanote) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 23610:
                                                  #0  0x00007f5abf27ed60 pango_fc_font_get_glyph (libpangoft2-1.0.so.0)
                                                  #1  0x00007f5abf27edb7 n/a ()
                                                  #2  0x00000000011d0134 n/a (/home/niuzhy/soft/leanote/Leanote)
Jun 15 08:31:05 Archhost systemd[1]: Started Process Core Dump (PID 23619/UID 0).

```

**Comment by RogerFang** [comment]
I have problem about starting leanote in my arch.

`Jun 15 11:57:05 roger systemd-coredump[16187]: Process 16177 (Leanote) of user 1000 dumped core.
                                               
                                               Stack trace of thread 16177:
                                               #0  0x00007fdf9465cd60 pango_fc_font_get_glyph (libp>
                                               #1  0x00007fdf9465cdb7 n/a (libpangoft2-1.0.so.0)
                                               #2  0x00000000011d0134 hb_font_funcs_set_glyph_exten>
                                               #3  0x00007fdf9465f159 n/a (libpangoft2-1.0.so.0)
                                               #4  0x00007fdf9954483e pango_shape_full (libpango-1.>
                                               #5  0x00007fdf9952ef17 n/a (libpango-1.0.so.0)
                                               #6  0x00007fdf9952f9b6 n/a (libpango-1.0.so.0)
                                               #7  0x00007fdf995300f7 n/a (libpango-1.0.so.0)
                                               #8  0x00007fdf99533a54 pango_layout_get_unknown_glyp>
                                               #9  0x00007fdf9a7e378c n/a (libgtk-x11-2.0.so.0)
                                               #10 0x00007fdf9a7e68a6 n/a (libgtk-x11-2.0.so.0)
                                               #11 0x00007fdf98dedb9d g_type_create_instance (libgo>
                                               #12 0x00007fdf98dce259 n/a (libgobject-2.0.so.0)
                                               #13 0x00007fdf98dcfa7d g_object_new_with_properties >
                                               #14 0x00007fdf98dd0532 g_object_new (libgobject-2.0.>
                                               #15 0x0000000001a31352 n/a (Leanote)
                                               #16 0x0000000001a3096b n/a (Leanote)
                                               #17 0x0000000001a2af89 n/a (Leanote)
                                               #18 0x0000000001a2aedb n/a (Leanote)
                                               #19 0x0000000003252916 _ZN9brightray16BrowserMainPar>
                                               #20 0x0000000002495a1e n/a (Leanote)
                                               #21 0x00000000024967cc n/a (Leanote)
                                               #22 0x000000000248f516 n/a (Leanote)
                                               #23 0x00000000011ac762 n/a (Leanote)
                                               #24 0x00000000011ab3f0 n/a (Leanote)
                                               #25 0x000000000314e8fc main (Leanote)
                                               #26 0x00007fdf9488706b __libc_start_main (libc.so.6)
                                               #27 0x000000000054ef99 _start (Leanote)`

**Comment by gentoor** [comment]
原因：harfbuzz harfbuzz-icu lib32-harfbuzz --- leanote 依赖1.7版本,升级到1.8出错.
解决办法：如果你的本地cache中有1.7版本，可以如下操作
cd /var/cache/pacman/pkg
pacman -U harfbuzz-1.7.6-2  harfbuzz-icu-1.7.6-2  lib32-harfbuzz-1.7.6-2

**Comment by skyox** [comment]
十分感谢，降级后可以用了
archlinux x64 降级 harfbuzz-1.7.6-2 harfbuzz-icu-1.7.6-2两个软件包就行啦，
 https://archive.archlinux.org/packages/h/harfbuzz/harfbuzz-1.7.6-2-x86_64.pkg.tar.xz
 https://archive.archlinux.org/packages/h/harfbuzz/harfbuzz-1.7.6-2-x86_64.pkg.tar.xz
