### ISSUE TITLE
没有看到一个笔记多个类别的设置

### ISSUE THREAD

**Issue by lijingjian001** [leanote/leanote#796]
没有看到一个笔记多个类别的设置,可以通过某一个类别查找。比如一个笔记既属于linux基础相关的,又属于安全配置相关的.那么既可以通过安全配置这个类别查找,又可以通过linux基础查找。这个,我觉得不满。
没有看到集成到自己项目的api,表示丫的,不能集成到自己项目中,表示不美,自主化程度不高。

**Comment by lealife** [comment]
你好, 可以通过标签来解决
