### ISSUE TITLE
多图笔记 filesTooLarge

### ISSUE THREAD

**Issue by PSilverQ** [leanote/leanote#798]
自建笔记服务，笔记中自带图片大小太大，没有使用nginx，可否通过修改配置文件修改图片附件最大限制
笔记中多是动图，单图大小也不是太大，大概1.6MB左右

![image](https://user-images.githubusercontent.com/32046378/42419653-f6a534d6-82eb-11e8-9971-0d65f0c9add8.png)

![image](https://user-images.githubusercontent.com/32046378/42419626-83ead004-82eb-11e8-891d-78f28796b7b7.png)

**Comment by appendage** [comment]
在admin界面 可以设置上传大小限制 默认是10M

**Comment by yonggithub** [comment]
![image](https://user-images.githubusercontent.com/25076827/52894668-c5125f00-31e8-11e9-886d-c73491e1a100.png)

**Comment by dxl3811051** [comment]
我的版本不对还是什么情况 为什么我找不到这个界面  我去了个人中心  没有这个页面啊  能告诉我下 如何进入这个页面么 我的版本是最新的2.6.1版本
