### ISSUE TITLE
关于编辑器的代码复制不能执行问题

### ISSUE THREAD

**Issue by linux-mac** [leanote/leanote#80]
环境：beta3 版本；OSX Yosemite 的 Safari 浏览器和 Windows 下的 Chrome 浏览器，的 shell 代码的空格问题，如下面一段：
```
mongorestore -h localhost -d leanote --directoryperdb leanote_install_data/  
```
1. 如果在note界面打开笔记，拷贝上面代码，将因空格问题而不能执行命令（***将空格删除，再加上空格，命令就能执行了，不知为何***）；
2. 但是，在blog界面，拷贝上面命令皆可以执行，不需要重写空格

不知道这是不是 BUG

**Comment by leanote** [comment]
Hi, 该问题确实是个BUG, 经排查已发现原因, 是因为代码编辑器的空格其实不是空格, 而是一个字符来占位. 我们会尽快修复.
