### ISSUE TITLE
这个项目还有没有更新计划之类的呢

### ISSUE THREAD

**Issue by hahaliu005** [leanote/leanote#800]
作为一名leanote的重度用户,看到它好久没更新了呀,服务器也越来越慢,我现在慌得一比

**Comment by duzhen1996** [comment]
@LianGee 图片居中很简单，在上下加<center></center>就好了，问件事，我还是出现了在网页上多图的笔记图片加载不出来的问题，开发人员说他们那边复现不出来，您能帮我看看吗：http://blog.leanote.com/post/454858191@qq.com/深度学习-吴恩达课程笔记

**Comment by istevenshen** [comment]
@duzhen1996 你的博客图片可以加载出来哦！

**Comment by LianGee** [comment]
@duzhen1996  用html标签的话，我还要markdown干啥... 想要的是类似这种`[@图片标题|left](url) `。
另外，图片加载不出来可能是之前服务器比较垃圾的原因，现在看起来服务器貌似稳定了不少。

**Comment by duzhen1996** [comment]
@istevenshen 你好兄弟，是所有的图片都可以加载出来吗，我那个博客一共30张左右的图片呢，我自己打开的之后只能加载出20张左右

**Comment by codexpage** [comment]
真的是好久没更新了，以为收费之后会更新的更快呢

**Comment by duzhen1996** [comment]
项目好像更新了？！

**Comment by lealife** [comment]
一直在优化呢
