### ISSUE TITLE
自建leanote，桌面客户端上传图片的无法加载，和web端不同步

### ISSUE THREAD

**Issue by jfrenhub** [leanote/leanote#819]
桌面端的图片链接：![EFAD6F749CCAF6FE942ECC6FC330E767.jpg](leanote://file/getAttach?fileId=5b98bde6bf06625b97000018)![EFAD6F749CCAF6FE942ECC6FC330E767.jpg](leanote://file/getAttach?fileId=5b98bde6bf06625b97000018)[EFAD6F749CCAF6FE942ECC6FC330E767.jpg](/api/file/getAttach?fileId=5b98bde6bf06625b97000018)
和web 端不一致

安卓端可以同步图片，

**Comment by Jeff-Ren** [comment]
(leanote://file/getAttach?fileId=5b98bde6bf06625b97000018)![EFAD6F749CCAF6FE942ECC6FC330E767.jpg](leanote://file/getAttach?fileId=5b98bde6bf06625b97000018)[EFAD6F749CCAF6FE942ECC6FC330E767.jpg](/api/file/getAttach?fileId=5b98bde6bf06625b97000018)

**Comment by Sesprie** [comment]
好像一直是这样，没有人去修复了，其实leanote挺好的，就是bug太多了

**Comment by wyufeng** [comment]
我的和你们有点不一样。web 和PC 桌面版插入的图片能顾相互正常显示。安卓手机显示不了。安卓手机上传的图片，桌面版需要改一下图片标题才能显示。然后改完安卓又不能显示了

**Comment by wyufeng** [comment]
或者会不会是故意搞的？  官方服务就没这BUG？？

**Comment by zhaijp** [comment]
可能是为了收费故意留的问题

**Comment by lealife** [comment]
https://github.com/leanote/leanote/wiki/QA#%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%B8%8D%E8%83%BD%E5%90%8C%E6%AD%A5%E5%9B%BE%E7%89%87

**Comment by lealife** [comment]
没有故意留BUG这一说
