### ISSUE TITLE
缴费不升级会员问题

### ISSUE THREAD

**Issue by Madiven** [leanote/leanote#830]
我大概在半个月前花费了50元去购买你们的会员，但是直到现在依然不是会员。发邮件，微博联系都没用，这个问题你们什么时候可以解决一下，我上微博看也不止我一个了吧！

**Comment by dispensable** [comment]
感觉他们跑路了，最近各种同步问题呀。

**Comment by wcb1996419** [comment]
> 感觉他们跑路了，最近各种同步问题呀。

他们问题多的狠，我已经不想用这个服务了。但是我还有1年会员

**Comment by dispensable** [comment]
> > 感觉他们跑路了，最近各种同步问题呀。
> 
> 他们问题多的狠，我已经不想用这个服务了。但是我还有1年会员

我也还有一年，还给家人买了一年。结果在国外的同步速度太差了，还经常504，安利失败不说，最近自己的同步都出问题。这23天之前的问题现在他们才回复。我还是早点备份数据准备跑路吧。

**Comment by Jenes9924** [comment]
可以自己搭服务器啊

**Comment by wcb1996419** [comment]
> 可以自己搭服务器啊
我没试过......自己搭的 我都是公开的博客才是

**Comment by Jenes9924** [comment]
> > > 感觉他们跑路了，最近各种同步问题呀。
> > 
> > 
> > 他们问题多的狠，我已经不想用这个服务了。但是我还有1年会员
> 
> 我也还有一年，还给家人买了一年。结果在国外的同步速度太差了，还经常504，安利失败不说，最近自己的同步都出问题。这23天之前的问题现在他们才回复。我还是早点备份数据准备跑路吧。

国外同步的速度差可能因为官网提供的服务器是在国内的，如果你在国外的话建议自己搭建服务器，速度快数据也能备份迁移

**Comment by lealife** [comment]
最近Leanote总是受到攻击, 服务确实不太稳定, 非常抱歉!!

**Comment by lealife** [comment]
@Madiven 你好, 请发邮件到 leanote@leanote.com, 非常抱歉, 没有及时回复

**Comment by Madiven** [comment]
> @Madiven 你好, 请发邮件到 leanote@leanote.com, 非常抱歉, 没有及时回复

我一开始就发邮箱反馈了，请问你们给反应了？
