### ISSUE TITLE
怎么在新的 vps 上复原之前备份的数据？

### ISSUE THREAD

**Issue by ziyangli** [leanote/leanote#834]
如题，已经在第一台 vps 上通过 admin 页面做了备份并下载了备份文件。

在新的 vps 上，怎么用这个备份文件？

莫非是走一遍源码搭建流程，然后在新的 admin 界面的备份及还原页里点还原？

**Comment by iWangJiaxiang** [comment]
在你创建备份的时候，每一条备份记录都会显示保存在服务器的绝对路径，复制备份文件并记录相对于leanote根目录的备份文件夹路径，你可以在新的服务器重新搭建一遍环境，然后把备份放到leanote备份文件夹，这样在网页上就会显示你复制的备份了，接下来，还原~

**Comment by lealife** [comment]
https://github.com/leanote/leanote/wiki/QA#%E5%BC%80%E5%8F%91%E7%89%88%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0leanote
