### ISSUE TITLE
客服根本就不回复你的问题！

### ISSUE THREAD

**Issue by wcb1996419** [leanote/leanote#837]
我发了 3个邮件。 时间跨度一个月了！ 
毫无回复，就在刚刚，我好不容易写好的课件，我一刷新，居然没有自动保存。
我的网络链接一直正常!!!

**Comment by Jenes9924** [comment]
请将问题详细描述一下，最好能够提供相应的证据以供开发者复现此Bug，否则的话无法判断这是软件的Bug还是使用者操作，亦或是环境导致的问题，谢谢

**Comment by lealife** [comment]
你好, 麻烦再发个邮件到 leanote@leanote.com
