### ISSUE TITLE
Mac markdown模式下无法正确输入汉字

### ISSUE THREAD

**Issue by xuyuri** [leanote/leanote#838]
![image](https://user-images.githubusercontent.com/9264579/49226594-0f721400-f422-11e8-8ecb-96a55b60f729.png)
输入完，按空格，就只显示字母，再按一次空格，后面就出来中文，每次都是出一堆字母一堆汉字，根本没法输入，普通笔记就没有这个问题，markdown模式下没法正确输入汉字。
![image](https://user-images.githubusercontent.com/9264579/49226624-24e73e00-f422-11e8-951e-8a05bc562222.png)

**Comment by leisiji** [comment]
linux也是这样情况，所以是怎么解决的？@xuyuri

**Comment by lealife** [comment]
![image](https://user-images.githubusercontent.com/1699428/49707206-57383d00-fc65-11e8-9e0f-aa3d0fae60cb.png)
切换到轻量模式
