### ISSUE TITLE
mac 版本客户端无法正常同步

### ISSUE THREAD

**Issue by liangchaob** [leanote/leanote#839]
![屏幕快照 2018-12-02 04.49.37.png](https://i.loli.net/2018/12/02/5c02f43292e30.png)
网络正常的状态下,修改历史笔记同步失败,新建笔记依旧同步失败,效果如图,经常反复出现此问题,问题出现几率不稳定,应该如何排查?
console log 如下
![屏幕快照 2018-12-02 04.54.33.png](https://i.loli.net/2018/12/02/5c02f521319ca.png)
![屏幕快照 2018-12-02 04.54.24.png](https://i.loli.net/2018/12/02/5c02f521ea77d.png)
![屏幕快照 2018-12-02 04.56.32.png](https://i.loli.net/2018/12/02/5c02f5a70b228.png)

**Comment by leisiji** [comment]
我的linux客户端也是出现这样的情况：
![image](https://user-images.githubusercontent.com/20882218/49334790-48c0a480-f619-11e8-8770-a418bb0a57ee.png)

**Comment by Dianaaaa** [comment]
+1

**Comment by lealife** [comment]
重启Leanote是否依旧存在?

**Comment by skyhiter** [comment]
我的macos 10.14； leanote 2.6.2也提示“同步失败，服务端笔记不存在”。

**Comment by lealife** [comment]
你好, 请复制这个笔记成新笔记试试

**Comment by skyhiter** [comment]
> 你好, 请复制这个笔记成新笔记试试
你好，
复制笔记成新笔记立马就可以同步了。
