### ISSUE TITLE
Code block quotes (```) breaks again.

### ISSUE THREAD

**Issue by Magicloud** [leanote/leanote#84]
Like in [this blog](http://magicloud.leanote.com/post/Make-pulseaudio-working-with-my-XDMCP-remote-desktop.), in step 1, the second code block. \`\`\` in source is converted to "\`.

**Comment by leanote** [comment]
你好, ```请单独一行, 比如:```代码放在这里```--------------------------------Leanote, Not Just A Notebook.--------------------------------                             Original Message                             Sender: 王世达<notifications@github.com>Recipient: leanote/leanote<leanote@noreply.github.com>Date: 星期五, 2月 27, 2015 12:02Subject: [leanote] Code block quotes (```) breaks again. (#84)Like in this blog, in step 1, the second code block. ``` in source is converted to "`.

**Comment by Magicloud** [comment]
很奇怪在编辑此文章时，单独一行会导致代码块上边多出一行，并且没有行号。现在又好了。
