### ISSUE TITLE
有些教程图挂了

### ISSUE THREAD

**Issue by rvier** [leanote/leanote#840]
https://s1.ax1x.com/2018/12/07/F3C1oT.jpg
[https://s1.ax1x.com/2018/12/07/F3C1oT.jpg](url)

**Comment by lealife** [comment]
你好, 经测试可以访问
![image](https://user-images.githubusercontent.com/1699428/49635189-f2e56580-fa39-11e8-8679-b1285fb16fe2.png)
可能是网络的问题

**Comment by rvier** [comment]
https://s1.ax1x.com/2018/12/07/F33oND.png
非常抱歉请你们再次检查一下，我尝试更换了网络环境但发现在蜂窝网络环境下也是这样。
这是我的网页上获取到的图片链接
希望对你们的诊断有帮助：
<img src="https://camo.githubusercontent.com/07dcf5c24c95222468051ad6a3b0139bd8ab5ef2/687474703a2f2f377869356d352e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f6c65616e6f74652f696d6167652f696d6167653030342e706e67" alt="enter image description here" data-canonical-src="http://7xi5m5.com1.z0.glb.clouddn.com/leanote/image/image004.png">
效果是这样的：
https://s1.ax1x.com/2018/12/07/F3Gqmt.jpg
是不是因为浏览器缓存而影响你们的诊断了呢？

**Comment by lealife** [comment]
你好, 这是github提供的服务
