### ISSUE TITLE
leanote docker

### ISSUE THREAD

**Issue by zxfishhack** [leanote/leanote#848]
编写了一个leanote的docker镜像，希望能放合并。

https://github.com/zxfishhack/leanote-docker

**Comment by lealife** [comment]
你好, 因Leanote会有files, public/upload文件夹, 这些文件夹内容都有可能会更改, 不知道能否支持?

**Comment by zxfishhack** [comment]
目前的build.sh脚本，会将leanote安装在容器内的/leanote/src/github.com/leanote/leanote目录，此目录下的files及public/upload文件夹会以卷的形式声明，在运行的时候可以映射至主机目录（或其他持久卷），这样此两个目录的修改会被另行存储，进行版本更新后，可复用。

编译环境为安装了go的alpine环境。镜像内未打包mongodb，mongodb需另行部署，目前我使用的app.conf中的mongodb配置如下：
# mongdb
db.host=mongodb
db.port=27017
db.dbname=leanote # required
db.username= leanote # if not exists, please leave it blank
db.password= leanote # if not exists, please leave it blank

run.sh修改如下：
#!/bin/sh

SCRIPTPATH=$(cd "$(dirname "$0")"; pwd)
"$SCRIPTPATH/leanote" -importPath github.com/leanote/leanote -srcPath "$SCRIPTPATH/src" -runMode prod

**Comment by lealife** [comment]
不错, 请问怎么合并呢?

**Comment by lealife** [comment]
我fork到leanote/下, 你来维护怎么样?

**Comment by zxfishhack** [comment]
好的

发自我的 iPhone

**Comment by lealife** [comment]
你好, 已邀请你

**Comment by lealife** [comment]
@zxfishhack 你好, https://github.com/leanote/leanote-docker 你已可以编辑
