### ISSUE TITLE
开源版本问题太多

### ISSUE THREAD

**Issue by ljw4010** [leanote/leanote#850]
1. 建议出一个使用手册
2.首页默认不是博客，是要重新配置理由 么？
3.demo用户不能删除，删除之后首页都无法登陆
作为开源项目，比较不错，等待更新

**Comment by lealife** [comment]
http://leanote.leanote.com/post/Leanote-manual-project

**Comment by ljw4010** [comment]
> http://leanote.leanote.com/post/Leanote-manual-proje
感谢，新手去学习了
