### ISSUE TITLE
执行脚本的时候报Failed to stat watched path /usr/local/leanote/bin/src/github.com/leanote/leanote/conf/routes 

### ISSUE THREAD

**Issue by benno233** [leanote/leanote#86]
TRACE 2015/03/08 10:31:37 i18n.go:119: Successfully loaded messages from file msg.zh
ERROR 2015/03/08 10:31:37 watcher.go:72: Failed to stat watched path /usr/local/leanote/bin/src/github.com/leanote/leanote/conf/routes : stat /usr/local/leanote/bin/src/github.com/leanote/leanote/conf/routes: no such file or directory
Go to /@tests to run the tests.

在conf 目录下确实不存在routes 文件

**Comment by Giina** [comment]
我直接下载的zip包里面是有的。github上面的源代码里面也是有这个文件的。要么是下载解压出了问题，要么是你误操作删除了吧？自己检查一下

**Comment by wangjianming** [comment]
我这边有下面这个错，却是也没有这个目录，暂时不影响功能，貌似和测试相关的？

ERROR 2015/03/24 14:28:57 watcher.go:72: Failed to stat watched path D:\Go\src/github.com\leanote\leanote/tests : GetFileAttributesEx D:\Go\src/github.com\leanote\leanote/tests: The system cannot find the file specified.

**Comment by leanote** [comment]
这个错误没关系

**Comment by Refactoring** [comment]
@leanote   @benno233 我测试了, 不包含源码的运行环境必须得有routes文件.    
如果没有routes文件可以正常访问，估计是你们的GOPATH环境变量中包含leanote的源码路径.

**Comment by lealife** [comment]
leanote-v1.0-beta.4 二进制版全平台发布, 包含linux, mac, windows三平台( 32 & 64 bit) 共 6种leanote二进制文件.

下载地址: http://leanote.org/#download
