### ISSUE TITLE
如何查看别人的博客

### ISSUE THREAD

**Issue by kidnapper1995** [leanote/leanote#891]
我如何搜索并查看别人的博客，博客都是私有的吗

**Comment by shenweiyan** [comment]
https://github.com/leanote/leanote/issues/803，列了一下蚂蚁笔记的一些博客。
蚂蚁笔记挺好的，万年没人维护，感觉要凉的节奏。赶紧往语雀转移了。

**Comment by lealife** [comment]
让别人把博客链接发你
