### ISSUE TITLE
为什么总是丢失笔记。。

### ISSUE THREAD

**Issue by wangjianming** [leanote/leanote#90]
我用的这个leanote-all-master.zip， 装在window上，写了笔记，一刷新就丢了

**Comment by leanote** [comment]
是否保存? ctrl+s ? 在http://leanote.com有相同的问题?

**Comment by wangjianming** [comment]
谢谢快速响应！
刚想起来了
可能我昨天操作的问题，我是a用户建笔记本，发现录入的一些笔记本来应该是b用户的，
然后登陆mongodb把笔记本的userid设置成b用户，
然后b登陆，操作建笔记有问题。


另外提一个问题，是不是只要完整备份mongodb，以后升级leanote就没问题了？

**Comment by leanote** [comment]
要备份:
1. mongodb数据库
2. files文件夹, 上传的图片,附件之类的
如果数据库有变更, 我们会有升级程序帮助升级的. 基本上备份这两种数据就没问题了.

**Comment by wangjianming** [comment]
好的非常感谢
