### ISSUE TITLE
发现个问题，客户端拥有强烈的内存泄漏，挂了几天占比mac下到了5g以上内存

### ISSUE THREAD

**Issue by ChenYCL** [leanote/leanote#902]

**Comment by hyfree** [comment]
建议每个一段时间重启一下客户端。

**Comment by lunaw** [comment]
...

**Comment by taozhang-tt** [comment]
我也遇到过这个问题，所以就卸载了客户端，使用编辑器直接写markdown文件，每天下班前同步一下到服务器上就完事了。

hyfree 我又看到你了，哈哈哈

> 建议每个一段时间重启一下客户端。

**Comment by ChenYCL** [comment]
都忘了有这个issue了，关了吧，多留点时间出去玩
