### ISSUE TITLE
自建的服务器，绑定域名，用域名在浏览器访问遇到问题

### ISSUE THREAD

**Issue by sprdlh** [leanote/leanote#904]
访问后后页面是这样的。
![image](https://user-images.githubusercontent.com/6218991/61268490-2d805f00-a7ce-11e9-9f77-ca90c1009b9a.png)
直接用loclehost：9000访问页面又正常

**Comment by Jesseyx** [comment]
要配置 site.url 吧

**Comment by sprdlh** [comment]
已经配置过site.url，不过没用，后面其实是在ngnix配置文件里添加   location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
     proxy_pass http://xxx.com    这行代码才解决的。

**Comment by Angryshark128** [comment]
> 已经配置过site.url，不过没用，后面其实是在ngnix配置文件里添加 location ~ .*.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
> proxy_pass http://xxx.com 这行代码才解决的。

这句代码应该是没办法解决的吧，我也遇到了这样的问题，转发时后台使用的是默认Nginx静态文件目录的，没有用leanote的静态文件目录，你后台咋解决的呢

**Comment by sprdlh** [comment]
附件是leanote绑定域名的网站配置文件，至于ngnix的配置我没去改，因为我不是专业的服务器运维人员，有些问题我也回答不上来，我是根据浏览器调试的信息在Google上找到相关的资料解决的问题。




------------------ 原始邮件 ------------------
发件人: "AngryShark"<notifications@github.com>;
发送时间: 2019年10月6日(星期天) 中午11:09
收件人: "leanote/leanote"<leanote@noreply.github.com>;
抄送: "605587735"<605587735@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [leanote/leanote] 自建的服务器，绑定域名，用域名在浏览器访问遇到问题 (#904)



 
已经配置过site.url，不过没用，后面其实是在ngnix配置文件里添加 location ~ .*.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
 proxy_pass http://xxx.com 这行代码才解决的。
  
这句代码应该是没办法解决的吧，我也遇到了这样的问题，转发时后台使用的是默认Nginx静态文件目录的，没有用leanote的静态文件目录，你后台咋解决的呢

**Comment by Angryshark128** [comment]
> 附件是leanote绑定域名的网站配置文件，至于ngnix的配置我没去改，因为我不是专业的服务器运维人员，有些问题我也回答不上来，我是根据浏览器调试的信息在Google上找到相关的资料解决的问题。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "AngryShark"<notifications@github.com>; 发送时间: 2019年10月6日(星期天) 中午11:09 收件人: "leanote/leanote"<leanote@noreply.github.com>; 抄送: "605587735"<605587735@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [leanote/leanote] 自建的服务器，绑定域名，用域名在浏览器访问遇到问题 (#904) 已经配置过site.url，不过没用，后面其实是在ngnix配置文件里添加 location ~ .*.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ { proxy_pass http://xxx.com 这行代码才解决的。 这句代码应该是没办法解决的吧，我也遇到了这样的问题，转发时后台使用的是默认Nginx静态文件目录的，没有用leanote的静态文件目录，你后台咋解决的呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Sorry，并没有看到附件呢

**Comment by sprdlh** [comment]
是这张图片。



------------------ 原始邮件 ------------------
发件人: "AngryShark"<notifications@github.com>;
发送时间: 2019年10月6日(星期天) 中午11:31
收件人: "leanote/leanote"<leanote@noreply.github.com>;
抄送: "605587735"<605587735@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [leanote/leanote] 自建的服务器，绑定域名，用域名在浏览器访问遇到问题 (#904)



 
附件是leanote绑定域名的网站配置文件，至于ngnix的配置我没去改，因为我不是专业的服务器运维人员，有些问题我也回答不上来，我是根据浏览器调试的信息在Google上找到相关的资料解决的问题。
 …
 ------------------ 原始邮件 ------------------ 发件人: "AngryShark"notifications@github.com; 发送时间: 2019年10月6日(星期天) 中午11:09 收件人: "leanote/leanote"leanote@noreply.github.com; 抄送: "605587735"605587735@qq.com;"Author"author@noreply.github.com; 主题: Re: [leanote/leanote] 自建的服务器，绑定域名，用域名在浏览器访问遇到问题 (#904) 已经配置过site.url，不过没用，后面其实是在ngnix配置文件里添加 location ~ .*.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ { proxy_pass http://xxx.com 这行代码才解决的。 这句代码应该是没办法解决的吧，我也遇到了这样的问题，转发时后台使用的是默认Nginx静态文件目录的，没有用leanote的静态文件目录，你后台咋解决的呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
Sorry，并没有看到附件呢

**Comment by Angryshark128** [comment]
![image](https://user-images.githubusercontent.com/39456225/66263912-cc48b480-e82d-11e9-90dc-e9b153efa7fa.png)
可是这个图片上面只是效果啊，没有相关配置文件,app.conf

**Comment by sprdlh** [comment]
upstream   domain.net  {
        server   ip:9000;
    }
server
{
	listen 80;
	listen 443 ssl;
    server_name www.domain.net domain.net;
    root /www/wwwroot/domain.net;
    
    location / {
            proxy_pass        http://domain.net;
            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
     location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
     proxy_pass http://domain.net;        
     }
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/domain.net/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/domain.net/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;


    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-72.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/domain.net.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log /dev/null;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log /dev/null; 
    }
    access_log  /www/wwwlogs/domain.net.log;
    error_log  /www/wwwlogs/domain.net.error.log;
}



------------------ 原始邮件 ------------------
发件人: "AngryShark"<notifications@github.com>;
发送时间: 2019年10月6日(星期天) 中午11:39
收件人: "leanote/leanote"<leanote@noreply.github.com>;
抄送: "605587735"<605587735@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [leanote/leanote] 自建的服务器，绑定域名，用域名在浏览器访问遇到问题 (#904)





 可是这个图片上面只是效果啊，没有相关配置文件,app.conf
