### ISSUE TITLE
强烈建议不要使用这个服务, 有极度危险的漏洞!!

### ISSUE THREAD

**Issue by qokelate** [leanote/leanote#908]
1. 客户端登录后会同步所有笔记到本地, 而且下次自动登录, 如果有其他人一起使用你的电脑就可以看到所有资料

2. 客户端登录后无论你怎么改密码/改用户名, 登录永远有效, 也就是你永远无法KICK以前的登录, 超级脑残设计!!!!

3. 基于1和2, 只要登录后把APPDATA的数据走, 你就能永远盗取这个账号的笔记!!!  真脑残!

**Comment by qokelate** [comment]
登录后自动同步, 同步完成后无论你做什么操作, 都无法避免别人看你的离线数据!!!

**Comment by skydreamever** [comment]
> 登录后自动同步, 同步完成后无论你做什么操作, 都无法避免别人看你的离线数据!!!

我觉得挺好用的，没啥重要资料拷走也无所谓，而且代码都是开源的，可以改呀，可以自己加上文章加密啥的代码不就可以了

**Comment by hyfree** [comment]
笔记的主要应用场景是个人使用
然后，绝大数笔记在 本地 的缓存都是可见的，包括有道云笔记、为知笔记、印象笔记等
然后，如果一定在公共电脑上使用，请使用网页版
然后，**桌面版请点击右下角--设置--更多--账户设置--账户管理--删除**，注销退出即可消除你的痕迹。

**Comment by qokelate** [comment]
客户端登录后无法你怎么改密码/改用户名, 登录永远有效   我是想不出有什么服务竟然改密码了原登录还有效, 按楼上的理解思维, 这是不是应该加粗标注该功能为  "全球首创" ?

**Comment by skydreamever** [comment]
> 是应该加粗标注该功能为

还是那句话，代码都是开源，可以自己改，这个项目能坚持到现在已经很好了，如果你感觉不满足你的要求可以自己改好，然后联系作者合并进去

**Comment by hyfree** [comment]
> 客户端登录后无论你怎么改密码/改用户名, 登录永远有效 我是想不出有什么服务竟然改密码了原登录还有效, 按楼上的理解思维, 这是不是应该加粗标注该功能为 "全球首创" ?

本身Leanne的登录动作确实有问题，但在普遍登录场景下问题被缩小了

**Comment by hyfree** [comment]
Leanne的登录动作是使用用户名/密码登录后，获取token作为权限证明。
我建议为第三方的开源生成单独的自定义token，用户可以在后台删除授权关系解除与第三方的授权关系。

**Comment by hyfree** [comment]
但本身，如果作为个人使用的部署用途，问题不是太严重。

**Comment by hyfree** [comment]
建议fork,然后请求合并

**Comment by swnb** [comment]
[https://github.com/leanote/leanote/blob/5e61291703a81514ef271ca01a379d151778895f/app/service/PwdService.go#L59](这里不是已经把 token 删了?)

**Comment by swnb** [comment]
看代码感觉没问题......

**Comment by Ariczh** [comment]
这个设计真的有问题，尤其是楼上某位自己的笔记没有私密内容不代表所有人使用都不涉及私密内容。
好好的讨论问题提出意见的issue，怎么还发展出粉圈文化不让说不好了？

**Comment by skydreamever** [comment]
> 这个设计真的有问题，尤其是楼上某位自己的笔记没有私密内容不代表所有人使用都不涉及私密内容。
> 好好的讨论问题提出意见的issue，怎么还发展出粉圈文化不让说不好了？

开源的server而已 不带你这样人身攻击的哦 
我也只是提出自己的观点 现在白嫖怪一个个都嫖上瘾了 动不动就就这个issue 那个issue 作者又不欠你的 你看看他提的issue的语气 哪有这样说话的？ 
还是那句话，代码都是开源，可以自己改，这个项目能坚持到现在已经很好了，（虽然很久没有更新了）如果你感觉不满足你的要求可以自己改好，然后联系作者合并进去 一个pull request比在这里issue中乱说话好多了

**Comment by lealife** [comment]
close
