### ISSUE TITLE
“我的笔记”跳转连接设置错误

### ISSUE THREAD

**Issue by wangjianming** [leanote/leanote#91]
leanote安装到http://10.180.143.110/

在另一个机器上访问http://10.180.143.110/，登陆后，点右上角“我的笔记”，然后跳转到http://localhost/note

**Comment by leanote** [comment]
请配置conf/app.conf的site.url

**Comment by wangjianming** [comment]
果然是这样，这个配置藏在目录D:\Go\src\github.com\leanote\leanote\conf中， 
thanks
