### ISSUE TITLE
默认监听ipv6

### ISSUE THREAD

**Issue by DefectingCat** [leanote/leanote#918]
安装完成后数据库链接都正常，但是web死活都没办法访问。检查配置文件的配置，监听地址，端口号都是正常的：
```
http.addr=0.0.0.0 # listen on all ip addresses
http.port=8070

site.url=http://0.0.0.0:8070/ # or http://x.com:8080, http://www.xx.com:9000
```

![](https://i.loli.net/2019/10/17/vr1sBPNhCVStipU.png)

但是web就是打不开，在别的的机器上测试telnet发现压根就没有监听8070端口。最后发现它监听的是ipv6的地址？

**机器没有ipv6公网地址，端口也没有被占用**

![](https://i.loli.net/2019/10/17/jpf8ltG4myYLIB5.png)

要修改什么地方才能使其监听ipv4呢

**Comment by DefectingCat** [comment]
system info

```
CentOS Linux release 7.7.1908 (Core)
Linux ecs.novalocal 5.3.6-1.el7.elrepo.x86_64 #1 SMP Fri Oct 11 17:24:39 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Nyako-233** [comment]
我也遇到了这个问题，请问要怎么解决？
