### ISSUE TITLE
采用二级域名代理内网的leanote,好多页面的url使用绝对路径,望解答

### ISSUE THREAD

**Issue by Refactoring** [leanote/leanote#93]
如题，我在服务器上启动了leanote,访问路径:localhost:9000.
因为端口限制，只能使用80端口，所以又使用apache代理。 用note.sitename.com代理localhost:9000.
访问后页面中好多链接都使用拼接的绝对路径(类似localhost:9000/public/js...)，获取了服务器端的配置的url.

不知道当时设计开发是，考虑什么原因将链接处理为服务端拼接的绝对路径？ 
如何修改，给个建议。

**Comment by lealife** [comment]
你好, 如果你使用了代理, 请将site.url设为代理的路径而不是服务器本地的路径.

**Comment by Refactoring** [comment]
-_-!!     一直以为site.url是本机运行需要配置的url.   文档中加个说明，避免再像我这样的情况出现啊,呵呵
