### ISSUE TITLE
同步信息失败 413 Request Entity Too Large， nginx/1.8.1

### ISSUE THREAD

**Issue by narutojxl** [leanote/leanote#939]
Hi， 用公司的网同步出现如下信息
>   ` 
   同步失败信息: <html>
    <head><title>413 Request Entity Too Large</title></head>
    <body bgcolor="white">
    <center><h1>413 Request Entity Too Large</h1></center>
     <hr><center>nginx/1.8.1</center>
    </body>
    </html>
`

 用自己的手机热点也同步failed， 感谢！

**Comment by hyfree** [comment]
请检查nginx上传大小限制

**Comment by narutojxl** [comment]
感谢回复！ 在电脑上没找到` /etc/nginx/` 和`/usr/local/nginx/` 两个目录,  也没有` /etc/php.ini`。

**Comment by hyfree** [comment]
如果你使用的是官方服务，请转到leanote-issue，或者加入反馈群
欢迎加入Leanote⑤，群聊号码：686860565
如果，你使用自建服务，请检查Nginx配置或者防火墙。并留下你自建的服务器的版本，Nginx版本，网站配置文件。
