### ISSUE TITLE
想要Leanote继续得到维护

### ISSUE THREAD

**Issue by shunf4** [leanote/leanote#942]
Leanote 烂爆了：
- 后端采用的 [revel](https://github.com/revel/revel) 框架已经许久没有维护；
- Electron 前端已经没有办法用最新的 Electron 编译，因为其代码已经过时，Arch/Manjaro 下使用还需要自己[放置额外的库](https://github.com/leanote/leanote.com-issue/issues/144)
- 几个仓库中的 issue 开发者基本已经懒得搭理，本仓库也已经快一年没有更新；原来的开发者似乎已经投入到 [Teakki](https://teakki.com/space/57373ba970e3cf1d38a2f337) 的开发中（似乎也已经不再更新了），Leanote 不再得到积极维护

但是，本人是特别喜欢这个软件的：
- 有包括网页端在内的各平台客户端；
- 可以直接当博客使用；
- 各种功能用起来还算顺手；
- 诸如自带 vim 模式的种种细节……

更重要的是，它的后端和各客户端以 GPL 协议开源，极大给予了用户对于数据的掌控和自由。完全自由的笔记软件中，有各平台客户端且功能足够日常个人笔记使用的，似乎只有 Leanote 一家了。（有什么好的麻烦大家推荐）

所以非常希望 Leanote 继续得到维护，带来更多功能。可惜自己能力不足什么也做不到，只能创建一个 Organization https://github.com/leanote-ng/desktop-app 把桌面端适配到 Electron 最新版。各位还有在用 Leanote 的吗，怎么看？

**Comment by hyfree** [comment]
干得漂亮
------------
https://github.com/hyfree/MoreNote

**Comment by ZuoAnZoom** [comment]
> Leanote 烂爆了：
> 
> * 后端采用的 [revel](https://github.com/revel/revel) 框架已经许久没有维护；
> * Electron 前端已经没有办法用最新的 Electron 编译，因为其代码已经过时，Arch/Manjaro 下使用还需要自己[放置额外的库](https://github.com/leanote/leanote.com-issue/issues/144)
> * 几个仓库中的 issue 开发者基本已经懒得搭理，本仓库也已经快一年没有更新；原来的开发者似乎已经投入到 [Teakki](https://teakki.com/space/57373ba970e3cf1d38a2f337) 的开发中（似乎也已经不再更新了），Leanote 不再得到积极维护
> 
> 但是，本人是特别喜欢这个软件的：
> 
> * 有包括网页端在内的各平台客户端；
> * 可以直接当博客使用；
> * 各种功能用起来还算顺手；
> * 诸如自带 vim 模式的种种细节……
> 
> 更重要的是，它的后端和各客户端以 GPL 协议开源，极大给予了用户对于数据的掌控和自由。完全自由的笔记软件中，有各平台客户端且功能足够日常个人笔记使用的，似乎只有 Leanote 一家了。（有什么好的麻烦大家推荐）
> 
> 所以非常希望 Leanote 继续得到维护，带来更多功能。可惜自己能力不足什么也做不到，只能创建一个 Organization https://github.com/leanote-ng/desktop-app 把桌面端适配到 Electron 最新版。各位还有在用 Leanote 的吗，怎么看？

以前用过一段时间 Leanote，很快就放弃了，感觉用不到点上去。目前在用 VNote，一直在维护更新，即使以后停止维护了，每个版本都很稳定，可以单独使用，数据库就一个文件夹可以直接坚果云同步，支持VIM操作，也支持本地图片保存和自动图床上传，各种功能都有，很喜欢，可以试试。

**Comment by hyfree** [comment]
把做个插件提供VNote到Leanote的云同步怎么样

**Comment by shunf4** [comment]
@ZuoAnZoom 如果是仅考虑桌面端，那显然有大量比蚂蚁笔记优秀的笔记软件。但是如果考虑到自建服务多端同步+有移动端，还是没有太多优于它的选项。

VNote 的同步文件可以被某个移动端笔记软件利用吗？

**Comment by hyfree** [comment]
应该可以。感觉也是笔记即服务的形式。
可以做个小程序把VNote的笔记同步到leanote笔记的服务器，仅限于markdown

**Comment by hyfree** [comment]
leanote有上传笔记和附件的API

**Comment by shunf4** [comment]
@hyfree 那其实没有必要用 Leanote，用一个自建或托管的 WebDAV 省事得多，只是上传图片附件这种附加需求比较麻烦…（不过很久之前体验过 Joplin 觉得 WebDAV 有同步速度和性能问题不知是不是错觉）

感觉蚂蚁笔记要想重新得到青睐需要比较大的改动和功能添加，比如支持多种存储后端（MongoDB、WebDAV 或者 Git）、更优的用户体验等等。否则还不如选择一个现有的正在维护的替代选项。

**Comment by hyfree** [comment]
@shunf4  应该暂时不会有这样的开发计划=》支持多种存储后端

**Comment by hyfree** [comment]
目前，我就是希望桌面端，移动端，争点气= =
服务器端还好，维持现状，够用就行。

**Comment by lealife** [comment]
@shunf4 
* revel是一开始就用的, 现在看来, 虽然更新了, 但它比较稳定, 如果我们替换revel, 成本非常大, 且没有任何意义
* desktop 使用的是旧的electron, 我们之前试图更新electron框架, 但我对electron小有失望, 因为我们要适应 win, mac, linux三平台, 几次升级electron都不好兼容linux, 所以我们用旧的. 如果你维护的版本在这3个平台测试良好, 那非常棒

**Comment by shunf4** [comment]
@lealife 我对 desktop 的改动是仅限于更新依赖到最新以及更新 electron 版本到最新，所以对 node_modules 做的迁出只是一个临时性 hack 性的改动，可能还需要一些整理。目前在 Linux 端能够正常运行。

**Comment by lealife** [comment]
@shunf4 可以用相对路径, 比如
main.js
`var pdfMain = require(path.resolve(appPath, './lib/pdf_main'));` 改成 `var pdfMain = require('./lib/pdf_main');`

**Comment by lealife** [comment]
@shunf4 看了你的提交, 兼容最新版electron, 主要就是 makeSingleInstance 不支持了, 已提交支持 https://github.com/leanote/desktop-app/commit/6e8cc693c4283c06306b038830a033d01d2433f6

**Comment by shenweiyan** [comment]
曾经的最爱，如今只能是默默关注一下，希望 Leanote 能更好的维护！

**Comment by tr15tan** [comment]
> @lealife 我对 desktop 的改动是仅限于更新依赖到最新以及更新 electron 版本到最新，所以对 node_modules 做的迁出只是一个临时性 hack 性的改动，可能还需要一些整理。目前在 Linux 端能够正常运行。

请问将electron升级到最新版本有什么好处？不是很了解electron

**Comment by shunf4** [comment]
@tr15tan 这样就可以在 Arch Linux 顺利运行了。否则因为系统中 Electron 的版本太新会缺库，跑不起来：#144

**Comment by hyfree** [comment]
😂服务器端和客户端的是怎么编译和debug的，你们是用什么开发工具。
有个开发环境手册就好了。

**Comment by shunf4** [comment]
@hyfree https://github.com/leanote/leanote/wiki/How-to-develop-leanote-%E5%A6%82%E4%BD%95%E5%BC%80%E5%8F%91leanote

**Comment by hyfree** [comment]
(◍˃̶ᗜ˂̶◍)✩想用goland，大佬

**Comment by taozhang-tt** [comment]
不舍得放弃蚂蚁笔记，但是已经放弃桌面端了，近乎偏执的不喜欢Electron开发的东西（可能是太穷，使用的丐版mac），改用web了

**Comment by yuchaoshui** [comment]
非常希望leanote能继续维护下去，个人非常喜欢笔记和博客同时拥有的这个功能。我搭建的私有自键leanote一直运行很稳定，自己把前端样式简单调了一下  https://note.yuchaoshui.com/

**Comment by shenweiyan** [comment]
> 非常希望leanote能继续维护下去，个人非常喜欢笔记和博客同时拥有的这个功能。我搭建的私有自键leanote一直运行很稳定，自己把前端样式简单调了一下 https://note.yuchaoshui.com/

点赞！你私有化部署的 leanote 用的是哪里的服务器？

**Comment by yuchaoshui** [comment]
> > 非常希望leanote能继续维护下去，个人非常喜欢笔记和博客同时拥有的这个功能。我搭建的私有自键leanote一直运行很稳定，自己把前端样式简单调了一下 https://note.yuchaoshui.com/
> 
> 点赞！你私有化部署的 leanote 用的是哪里的服务器？

在阿里云买的

**Comment by taozhang-tt** [comment]
> > 非常希望leanote能继续维护下去，个人非常喜欢笔记和博客同时拥有的这个功能。我搭建的私有自键leanote一直运行很稳定，自己把前端样式简单调了一下 https://note.yuchaoshui.com/
> 
> 点赞！你私有化部署的 leanote 用的是哪里的服务器？

我用的腾讯云轻量应用服务器，挺稳定的，供你参考一下

**Comment by jwh199588** [comment]
@yuchaoshui  能不能把你的leanote主题分享一下

**Comment by thunder951413** [comment]
请问有人遇到用nginx代理之后上传附件或者照片之类的都失败的问题吗？
可能不用nginx也有这些问题。

**Comment by hyfree** [comment]
> 请问有人遇到用nginx代理之后上传附件或者照片之类的都失败的问题吗？
> 可能不用nginx也有这些问题。

建议另开一个issue描述一下你的搭建环境，软件版本，NGINX配置，上传失败的返回的错误信息(浏览器f12)。
