### ISSUE TITLE
400 Bad Request: malformed Host header after installing Let's Encrypt

### ISSUE THREAD

**Issue by cyayung** [leanote/leanote#943]
400 Bad Request: malformed Host header

**Comment by hyfree** [comment]
您好，请提供更多您的服务器环境信息

- 系统版本比如centos7XXXXXXXX 和内核信息

- 您是如何安装leanote的。docker还是二进制安装还是编译安装。

- 如果是二进制安装，请提供您的leanote安装版本

- 如果是编译安装，请提供您的对应代码版本

- 最好附上您的安装过程和输出日志（可选）

- 如果您是使用docker镜像安装，请提供您的docker版本和docker镜像版本或者对应地址，并且提供您的docker配置信息（可选）

- 您的服务器配置信息：比如nginx版本和配置信息（可选）

- 其他任何您觉得可能有帮助的信息

如果有大佬在线的话，可能会看到您的信息。

**Comment by lealife** [comment]
Please use nginx to handle ssl
