### ISSUE TITLE
我用了快一年的高级会员了，为什么我的博客图片最近都消失了？

### ISSUE THREAD

**Issue by zsp108** [leanote/leanote#953]
我用了快一年的高级会员了，为什么我的博客图片最近都消失了？如题，还找不到客服啥的，只能这边找了，麻烦解释下，谢谢

**Comment by shunf4** [comment]
他们估计不怎么管这边了吧…

**Comment by zsp108** [comment]
> 他们估计不怎么管这边了吧…
应该是，好像都不维护了，

**Comment by hyfree** [comment]
https://github.com/leanote/leanote.com-issue/issues/222 @zsp108

**Comment by raymond-yan** [comment]
我的笔记图片也是消失了，看请求的错误回应是 ERR_SSL_VERSION_OR_CIPHER_MISMATCH

应该是服务器的SSL证书配置有问题，不是很大的问题，官方有人管理一下吗。

**Comment by weijie-he** [comment]
我也是这样，应该就是楼上说的SSL证书的问题。
我用Chrome浏览器显示不出图片，但用火狐浏览器就可以，你们可以试下。
