### ISSUE TITLE
付钱升级但却没升级

### ISSUE THREAD

**Issue by cendeavor** [leanote/leanote#961]
充了50元升级高级，但是两天了账户还没升级，写邮件也不给受理，简直就是敲诈！！！

**Comment by Deteriorator** [comment]
> 充了50元升级高级，但是两天了账户还没升级，写邮件也不给受理，简直就是敲诈！！！

估计跑路了，没更新了

**Comment by lealife** [comment]
抱歉, 请联系 leanote@leanote.com
