### ISSUE TITLE
官网无法登录，笔记无法同步

### ISSUE THREAD

**Issue by monkxueit** [leanote/leanote#965]
同步时，报“网络异常，请检查网络或稍后再试”
官网登录时，报“504 Gateway Time-out”

**Comment by rexlevin** [comment]
跑路了吧？
官网没有任何说明，代码很久不更新，issue没有人解决，猜测是没有资金做不下去了，然后逃避了呗，所以什么交代都没有。

**Comment by strugglebak** [comment]
> 跑路了吧？
> 官网没有任何说明，代码很久不更新，issue没有人解决，猜测是没有资金做不下去了，然后逃避了呗，所以什么交代都没有。

卧槽，我现在也登录不上去了，也不同步了。。。。

**Comment by strugglebak** [comment]
我虽然想到有这么一天，但没想到这么快。。。。

**Comment by fanlushuai** [comment]
同样
![image](https://user-images.githubusercontent.com/21078607/102909173-8835e400-44b3-11eb-901b-6c74edc8ad97.png)

真要跑路了？

**Comment by DonkeXu** [comment]
啊这，至少要留个缓冲期吧.....

**Comment by lealife** [comment]
DDOS攻击
