### ISSUE TITLE
Fork 了个新项目准备继续维护下去，求轻踩~

### ISSUE THREAD

**Issue by ssoor** [leanote/leanote#977]
新项目地址：https://github.com/coocn-cn/leanote

这个项目好像已经停止维护了，好久没有新的代码更新了，刚好自己也想加点功能。

目前准备做的事情
1. 完善部署文档，让项目可以正常部署
2. 添加离线功能，服务器关闭也有本地备份
3. 添加博客同步功能，把笔记同步发布到其他博客平台中去。

**Comment by ssoor** [comment]
如果作者愿意的话，可以给个权限，在这个项目上进行后续更新。

**Comment by lealife** [comment]
👍

**Comment by huangguangkan** [comment]
👍
